--AUTO GENERATED BY ITR2 ITEM UPDATE SCRIPT--
local Items = {

	Probes = {
		ProbeSack = "/Game/ITR2/BPs/Items/Probes/BP_ProbeSack.BP_ProbeSack_C",
		RadiusAmmo_Probe = "/Game/ITR2/BPs/Items/Probes/BP_RadiusAmmo_Probe.BP_RadiusAmmo_Probe_C",
	},

	Firearms = {

		Primary = {

			AK74 = {
				AK_74_Mag_Red = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Red.BP_AK_74_Mag_Red_C",
				AK_74_Mag_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Black.BP_AK_74_Mag_Black_C",
				AK_74_Mag_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Long.BP_AK_74_Mag_Long_C",
				AK74_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74_Modular_Base.BP_AK74_Modular_Base_C",
				AK74_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74_Modular_S.BP_AK74_Modular_S_C",
				AKSu_Modular_base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AKSu_Modular_base.BP_AKSu_Modular_base_C",
				AKSu_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AKSu_Modular_S.BP_AKSu_Modular_S_C",

				AK74_Parts = {
					Ak74_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AK74_Parts/BP_Ak74_Barrel_Base.BP_Ak74_Barrel_Base_C",
					Ak74_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AK74_Parts/BP_Ak74_Barrel_Base_S.BP_Ak74_Barrel_Base_S_C",
				},

				AKSu_parts = {
					AKSu_Handguard_Wood1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Handguard_Wood1.BP_AKSu_Handguard_Wood1_C",
					AKSu_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Handguard_Railed.BP_AKSu_Handguard_Railed_C",
					AKSu_Handguard_Wood_Old = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Handguard_Wood_Old.BP_AKSu_Handguard_Wood_Old_C",
					AKSu_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Barrel_Base.BP_AKSu_Barrel_Base_C",
					AKSu_Barrel_Base_Rusty = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Barrel_Base_Rusty.BP_AKSu_Barrel_Base_Rusty_C",
					AKSu_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Lid_Basic.BP_AKSu_Lid_Basic_C",
					AKSu_Lid_Basic_Rusty = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Lid_Basic_Rusty.BP_AKSu_Lid_Basic_Rusty_C",
					AKSu_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Lid_Railed.BP_AKSu_Lid_Railed_C",
				},

			},

			AKM = {
				AKM_Mag_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Mag_Short.BP_AKM_Mag_Short_C",
				AKM_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Mag.BP_AKM_Mag_C",
				AKM_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Modular_Base.BP_AKM_Modular_Base_C",
				AKM_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Modular_S.BP_AKM_Modular_S_C",

				AKM_Parts = {
					AKM_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/AKM_Parts/BP_AKM_Barrel_Base.BP_AKM_Barrel_Base_C",
					AKM_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/AKM_Parts/BP_AKM_Barrel_Base_S.BP_AKM_Barrel_Base_S_C",
				},

			},

			Groza = {
				Groza_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza_Mag.BP_Groza_Mag_C",
				Groza_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza_S.BP_Groza_S_C",
				Groza = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza.BP_Groza_C",

				Groza_Parts = {
					Rail_Groza = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/Groza_Parts/BP_Rail_Groza.BP_Rail_Groza_C",
				},

			},

			Saiga = {
				Saiga_Mag_Short2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Mag_Short2.BP_Saiga_Mag_Short2_C",
				Saiga_Mag_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Mag_Long.BP_Saiga_Mag_Long_C",
				Saiga_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Modular_Base.BP_Saiga_Modular_Base_C",
				Saiga_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Modular_S.BP_Saiga_Modular_S_C",

				Saiga_parts = {
					Saiga_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Barrel_Long.BP_Saiga_Barrel_Long_C",
					Saiga_Barrel_Long_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Barrel_Long_S.BP_Saiga_Barrel_Long_S_C",
					Saiga_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Barrel_Short.BP_Saiga_Barrel_Short_C",
					Saiga_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Handguard_Base.BP_Saiga_Handguard_Base_C",
					Saiga_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Handguard_Railed.BP_Saiga_Handguard_Railed_C",
					Saiga_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Lid_Basic.BP_Saiga_Lid_Basic_C",
					Saiga_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Lid_Railed.BP_Saiga_Lid_Railed_C",
				},

			},

			Val_and_VSS = {
				VSS_Mag_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VSS_Mag_Short.BP_VSS_Mag_Short_C",
				AS_Val_Mag_Med = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_AS_Val_Mag_Med.BP_AS_Val_Mag_Med_C",
				VAL_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VAL_Modular_Base.BP_VAL_Modular_Base_C",
				VAL_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VAL_Modular_S.BP_VAL_Modular_S_C",

				Val_Details = {
					Val_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_Val_Lid_Basic.BP_Val_Lid_Basic_C",
					Val_Lid_Rail = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_Val_Lid_Rail.BP_Val_Lid_Rail_C",
					VAL_StockAdapter_AK = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_VAL_StockAdapter_AK.BP_VAL_StockAdapter_AK_C",
					VAL_Handguard_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_VAL_Handguard_1.BP_VAL_Handguard_1_C",
					VAL_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_VAL_Handguard_Railed.BP_VAL_Handguard_Railed_C",
					VAL_Stock_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_VAL_Stock_Handle.BP_VAL_Stock_Handle_C",
					Val_Handle_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_Val_Handle_Plastic.BP_Val_Handle_Plastic_C",
					Val_Handle_Plastic_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_Val_Handle_Plastic_2.BP_Val_Handle_Plastic_2_C",
					VAL_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_VAL_Barrel_Base.BP_VAL_Barrel_Base_C",
					VAL_Barrel_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_VAL_Barrel_Railed.BP_VAL_Barrel_Railed_C",
					VAL_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/Val_Details/BP_VAL_Barrel_Base_S.BP_VAL_Barrel_Base_S_C",
				},

			},

			Bizon = {
				Bizon_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_Mag.BP_Bizon_Mag_C",
				Bizon_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_Modular_Base.BP_Bizon_Modular_Base_C",
				Bizon_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_Modular_S.BP_Bizon_Modular_S_C",

				Bizon_Parts = {
					Bizon_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Barrel_Base.BP_Bizon_Barrel_Base_C",
					Bizon_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Barrel_Base_S.BP_Bizon_Barrel_Base_S_C",
					Bizon_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Barrel_Long.BP_Bizon_Barrel_Long_C",
					Bizon_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Handguard_Base.BP_Bizon_Handguard_Base_C",
					Bizon_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Handguard_Railed.BP_Bizon_Handguard_Railed_C",
					Bizon_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Lid_Basic.BP_Bizon_Lid_Basic_C",
					Bizon_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Lid_Railed.BP_Bizon_Lid_Railed_C",
				},

			},

			M4A1 = {
				M4A1_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1_Mag.BP_M4A1_Mag_C",
				M4A1_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1_Modular_Base.BP_M4A1_Modular_Base_C",
				M4A1_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1_Modular_S.BP_M4A1_Modular_S_C",

				M4A1_Parts = {
					Rail_M4A1_Classik = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_Rail_M4A1_Classik.BP_Rail_M4A1_Classik_C",
					M4A1_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Short.BP_M4A1_Barrel_Short_C",
					M4A1_Barrel_Short_S = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Short_S.BP_M4A1_Barrel_Short_S_C",
					M4A1_Barrel_Medium = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Medium.BP_M4A1_Barrel_Medium_C",
					M4A1_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Long.BP_M4A1_Barrel_Long_C",
					M4A1_Handguard_Classik = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Classik.BP_M4A1_Handguard_Classik_C",
					M4A1_Handguard_Classik_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Classik_2.BP_M4A1_Handguard_Classik_2_C",
					M4A1_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Railed.BP_M4A1_Handguard_Railed_C",
					M4A1_Handguard_Railed_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Railed_2.BP_M4A1_Handguard_Railed_2_C",
					M4A1_Handguard_RailedSP_M1 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedSP_M1.BP_M4A1_Handguard_RailedSP_M1_C",
					M4A1_Handguard_RailedSP_M2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedSP_M2.BP_M4A1_Handguard_RailedSP_M2_C",
					M4A1_Handguard_RailedSP_M3 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedSP_M3.BP_M4A1_Handguard_RailedSP_M3_C",
					M4A1_Handguard_RailedKTT_M1 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M1.BP_M4A1_Handguard_RailedKTT_M1_C",
					M4A1_Handguard_RailedKTT_M2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M2.BP_M4A1_Handguard_RailedKTT_M2_C",
					M4A1_Handguard_RailedKTT_M3 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M3.BP_M4A1_Handguard_RailedKTT_M3_C",
					M4A1_Handguard_RailedKTT_M4 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M4.BP_M4A1_Handguard_RailedKTT_M4_C",
					M4A1_Handguard_RailedKTT_M5 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M5.BP_M4A1_Handguard_RailedKTT_M5_C",
					M4A1_GasBlock_Classik = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_GasBlock_Classik.BP_M4A1_GasBlock_Classik_C",
					M4A1_GasBlock_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_GasBlock_Railed.BP_M4A1_GasBlock_Railed_C",
					M4A1_GasBlock_Inner = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_GasBlock_Inner.BP_M4A1_GasBlock_Inner_C",
				},

			},

			SVD = {
				SVD_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_Mag.BP_SVD_Mag_C",
				SVD_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_Modular_Base.BP_SVD_Modular_Base_C",
				SVD_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_Modular_S.BP_SVD_Modular_S_C",

				SVDParts = {
					SVD_Barrel_AdapterOnBarrell = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_AdapterOnBarrell.BP_SVD_Barrel_AdapterOnBarrell_C",
					SVD_Barrel_Muzzle_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_Muzzle_1.BP_SVD_Barrel_Muzzle_1_C",
					SVD_Stock_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Stock_Handle.BP_SVD_Stock_Handle_C",
					SVD_Stock_Handle_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Stock_Handle_S.BP_SVD_Stock_Handle_S_C",
					SVD_StockAdapter_AR_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_StockAdapter_AR_1.BP_SVD_StockAdapter_AR_1_C",
					SVD_Lid_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Lid_Base.BP_SVD_Lid_Base_C",
					SVD_Handguard_Railed_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Handguard_Railed_1.BP_SVD_Handguard_Railed_1_C",
					SVD_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Handguard_Base.BP_SVD_Handguard_Base_C",
					SVD_Handguard_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Handguard_S.BP_SVD_Handguard_S_C",
					SVD_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_Base.BP_SVD_Barrel_Base_C",
					SVD_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_Base_S.BP_SVD_Barrel_Base_S_C",
					SVD_Barrel_AdapterOnBarrell = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_AdapterOnBarrell.BP_SVD_Barrel_AdapterOnBarrell_C",
				},

			},

			G36 = {
				G36_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_Mag.BP_G36_Mag_C",
				G36_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_Modular_Base.BP_G36_Modular_Base_C",
				G36_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_Modular_S.BP_G36_Modular_S_C",

				G36_Parts = {
					Rail_Plank_G36 = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_Plank_G36.BP_Rail_Plank_G36_C",
					Rail_Plank_G36_v2 = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_Plank_G36_v2.BP_Rail_Plank_G36_v2_C",
					Rail_G36 = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_G36.BP_Rail_G36_C",
					Rail_G36_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_G36_Short.BP_Rail_G36_Short_C",
					Rail_G36_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_G36_Long.BP_Rail_G36_Long_C",
					G36_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Short.BP_G36_Barrel_Short_C",
					G36_Barrel_Short_S = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Short_S.BP_G36_Barrel_Short_S_C",
					G36_Barrel_Medium = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Medium.BP_G36_Barrel_Medium_C",
					G36_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Long.BP_G36_Barrel_Long_C",
					G36_Handguard_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Short.BP_G36_Handguard_Short_C",
					G36_Handguard_Medium = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Medium.BP_G36_Handguard_Medium_C",
					G36_Handguard_Medium_S = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Medium_S.BP_G36_Handguard_Medium_S_C",
					G36_Handguard_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Long.BP_G36_Handguard_Long_C",
					G36_Stock_Folding = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Stock_Folding.BP_G36_Stock_Folding_C",
					G36_Stock_Teleskopic = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Stock_Teleskopic.BP_G36_Stock_Teleskopic_C",
				},

			},

			BenelliM2 = {
				BenelliM2_6_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_6_Mag.BP_BenelliM2_6_Mag_C",
				BenelliM2_8_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_8_Mag.BP_BenelliM2_8_Mag_C",
				BenelliM2_2_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_2_Mag.BP_BenelliM2_2_Mag_C",
				BenelliM2_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_Modular_Base.BP_BenelliM2_Modular_Base_C",
				BenelliM2_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_Modular_S.BP_BenelliM2_Modular_S_C",

				Benelli_Parts = {
					Rail_BenelliM2 = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Rail_BenelliM2.BP_Rail_BenelliM2_C",
					Rail_BenelliM2_Underbarrel = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Rail_BenelliM2_Underbarrel.BP_Rail_BenelliM2_Underbarrel_C",
					Benelli_Stock_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Stock_Handle.BP_Benelli_Stock_Handle_C",
					Benelli_Stock_Handle_Ergo = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Stock_Handle_Ergo.BP_Benelli_Stock_Handle_Ergo_C",
					Benelli_Handle_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handle_1.BP_Benelli_Handle_1_C",
					Benelli_Handle_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handle_2.BP_Benelli_Handle_2_C",
					Benelli_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Base.BP_Benelli_Barrel_Base_C",
					Benelli_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Base_S.BP_Benelli_Barrel_Base_S_C",
					Benelli_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Short.BP_Benelli_Barrel_Short_C",
					Benelli_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Long.BP_Benelli_Barrel_Long_C",
					Benelli_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handguard_Base.BP_Benelli_Handguard_Base_C",
					Benelli_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handguard_Railed.BP_Benelli_Handguard_Railed_C",
					Benelli_Handguard_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handguard_Short.BP_Benelli_Handguard_Short_C",
				},

			},

			SR25 = {
				SR25_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/BP_SR25_Mag.BP_SR25_Mag_C",
				SR25_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/BP_SR25_Modular_Base.BP_SR25_Modular_Base_C",
				SR25_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/BP_SR25_Modular_S.BP_SR25_Modular_S_C",

				SR25_Parts = {
					SR25_Barrel_Small = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Small.BP_SR25_Barrel_Small_C",
					SR25_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Base.BP_SR25_Barrel_Base_C",
					SR25_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Base_S.BP_SR25_Barrel_Base_S_C",
					SR25_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Long.BP_SR25_Barrel_Long_C",
					SR25_Handguard_Railed_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Handguard_Railed_1.BP_SR25_Handguard_Railed_1_C",
				},

			},

			MP9 = {
				MP9_Mag30 = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/BP_MP9_Mag30.BP_MP9_Mag30_C",
				MP9_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/BP_MP9_Modular_Base.BP_MP9_Modular_Base_C",
				MP9_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/BP_MP9_Modular_S.BP_MP9_Modular_S_C",

				MP9_parts = {
					Rail_MP9_DownRail = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_Rail_MP9_DownRail.BP_Rail_MP9_DownRail_C",
					Rail_MP9_LeftRail = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_Rail_MP9_LeftRail.BP_Rail_MP9_LeftRail_C",
					Rail_MP9_RightRail = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_Rail_MP9_RightRail.BP_Rail_MP9_RightRail_C",
					MP9_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_MP9_Handguard_Railed.BP_MP9_Handguard_Railed_C",
					MP9_Stock_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_MP9_Stock_Base.BP_MP9_Stock_Base_C",
				},

			},

			Vityaz = {
				Vityaz_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/BP_Vityaz_Mag.BP_Vityaz_Mag_C",
				Vityaz_Modular = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/BP_Vityaz_Modular.BP_Vityaz_Modular_C",
				Vityaz_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/BP_Vityaz_Modular_S.BP_Vityaz_Modular_S_C",

				Vityaz_parts = {
					Ak74_Vityaz_Plastic_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Ak74_Vityaz_Plastic_Black.BP_Ak74_Vityaz_Plastic_Black_C",
					Vityaz_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Barrel_Base.BP_Vityaz_Barrel_Base_C",
					Vityaz_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Barrel_Base_S.BP_Vityaz_Barrel_Base_S_C",
					Vityaz_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Barrel_Long.BP_Vityaz_Barrel_Long_C",
					Vityaz_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Lid_Basic.BP_Vityaz_Lid_Basic_C",
					Vityaz_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Lid_Railed.BP_Vityaz_Lid_Railed_C",
				},

			},

			KEDR_PP_91 = {
				KEDR_PP_91_Mag_20 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Mag_20.BP_KEDR_PP-91_Mag_20_C",
				KEDR_PP_91_Mag_30 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Mag_30.BP_KEDR_PP-91_Mag_30_C",
				KEDR_PP_91_Mag_40 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Mag_40.BP_KEDR_PP-91_Mag_40_C",
				KEDR_PP_91_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Modular_Base.BP_KEDR_PP-91_Modular_Base_C",
				KEDR_PP_91_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Modular_S.BP_KEDR_PP-91_Modular_S_C",

				Kedr_Parts = {
					Rail_Kedr_HandGuard_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Rail_Kedr_HandGuard_Long.BP_Rail_Kedr_HandGuard_Long_C",
					Rail_Kedr_HandGuard_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Rail_Kedr_HandGuard_Short.BP_Rail_Kedr_HandGuard_Short_C",
					Kedr_Stock_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Stock_Base.BP_Kedr_Stock_Base_C",
					Kedr_StockAdapter_AK = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_StockAdapter_AK.BP_Kedr_StockAdapter_AK_C",
					Kedr_StockAdapter_AR = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_StockAdapter_AR.BP_Kedr_StockAdapter_AR_C",
					Kedr_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Lid_Basic.BP_Kedr_Lid_Basic_C",
					Kedr_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Handguard_Railed.BP_Kedr_Handguard_Railed_C",
					Kedr_Handguard_Railed_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Handguard_Railed_2.BP_Kedr_Handguard_Railed_2_C",
				},

			},

			Mosin = {
				Mosin_Mag_Internal = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_Mag_Internal.BP_Mosin_Mag_Internal_C",
				Mosin_Clip = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_Clip.BP_Mosin_Clip_C",
				Mosin_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_Mag.BP_Mosin_Mag_C",
				Mosin_modular = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_modular.BP_Mosin_modular_C",
				Mosin_modular_S_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_modular_S_2.BP_Mosin_modular_S_2_C",

				Mosin_parts = {
					Mosin_ForeSight = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_ForeSight.BP_Mosin_ForeSight_C",
					Mosin_ForeSight_Rail = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_ForeSight_Rail.BP_Mosin_ForeSight_Rail_C",
					Mosin_KochetovaBase = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_KochetovaBase.BP_Mosin_KochetovaBase_C",
					Scope_PU_Rail = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Scope_PU_Rail.BP_Scope_PU_Rail_C",
					Side_Mosin_Bandolier = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Side_Mosin_Bandolier.BP_Side_Mosin_Bandolier_C",
					Mosin_Bandolier_Stock_L2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Bandolier_Stock_L2.BP_Mosin_Bandolier_Stock_L2_C",
					Mosin_Bandolier_Stock_R2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Bandolier_Stock_R2.BP_Mosin_Bandolier_Stock_R2_C",
					Mosin_LongStock_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Wood.BP_Mosin_LongStock_Wood_C",
					Mosin_LongStock_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Plastic.BP_Mosin_LongStock_Plastic_C",
					Mosin_LongStock_Plastic_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Plastic_2.BP_Mosin_LongStock_Plastic_2_C",
					Mosin_LongStock_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Short.BP_Mosin_LongStock_Short_C",
					Mosin_LongStock_Short_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Short_2.BP_Mosin_LongStock_Short_2_C",
					Mosin_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Barrel_Base.BP_Mosin_Barrel_Base_C",
					Mosin_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Barrel_Short.BP_Mosin_Barrel_Short_C",
					Mosin_Barrel_Short_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Barrel_Short_2.BP_Mosin_Barrel_Short_2_C",
				},

			},

			SKS = {
				SKS_Mag_Internal = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_Mag_Internal.BP_SKS_Mag_Internal_C",
				SKS_Clip = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_Clip.BP_SKS_Clip_C",
				SKS_Mag_20 = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_Mag_20.BP_SKS_Mag_20_C",
				SKS_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_Modular_Base.BP_SKS_Modular_Base_C",
				SKS_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_Modular_S.BP_SKS_Modular_S_C",

				SKS_Parts = {
					SKS_DovetailBase = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_DovetailBase.BP_SKS_DovetailBase_C",
					SKS_ForeSight_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_ForeSight_Base.BP_SKS_ForeSight_Base_C",
					SKS_ForeSight_Rail = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_ForeSight_Rail.BP_SKS_ForeSight_Rail_C",
					SKS_Upper_BigRail = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_Upper_BigRail.BP_SKS_Upper_BigRail_C",
					SKS_LongStock_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_LongStock_Wood.BP_SKS_LongStock_Wood_C",
					SKS_LongStock_Wood_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_LongStock_Wood_2.BP_SKS_LongStock_Wood_2_C",
					SKS_LongStock_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_LongStock_Plastic.BP_SKS_LongStock_Plastic_C",
					SKS_Stock_Folding = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_Stock_Folding.BP_SKS_Stock_Folding_C",
					SKS_Handle_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_Handle_Plastic.BP_SKS_Handle_Plastic_C",
					SKS_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_Barrel_Base.BP_SKS_Barrel_Base_C",
					SKS_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_Barrel_Base_S.BP_SKS_Barrel_Base_S_C",
					SKS_StockAdapter_AKBS = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_StockAdapter_AKBS.BP_SKS_StockAdapter_AKBS_C",
					SKS_StockAdapter_AR = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/SKS_Parts/BP_SKS_StockAdapter_AR.BP_SKS_StockAdapter_AR_C",
				},

			},

			G3 = {
				G3_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/BP_G3_Mag.BP_G3_Mag_C",
				G3_Standart_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/BP_G3_Standart_Modular_Base.BP_G3_Standart_Modular_Base_C",

				G3_Parts = {
					G3_Barrel_Muzzle = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/G3_Parts/BP_G3_Barrel_Muzzle.BP_G3_Barrel_Muzzle_C",
					G3_Barrel_Standart_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/G3_Parts/BP_G3_Barrel_Standart_Base.BP_G3_Barrel_Standart_Base_C",
					G3_StockAdapter_Adapter = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/G3_Parts/BP_G3_StockAdapter_Adapter.BP_G3_StockAdapter_Adapter_C",
					G3_StockAdapter_AdapterWithStock = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/G3_Parts/BP_G3_StockAdapter_AdapterWithStock.BP_G3_StockAdapter_AdapterWithStock_C",
					G3_Handle_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/G3_Parts/BP_G3_Handle_Basic.BP_G3_Handle_Basic_C",
					G3_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/G3_Parts/BP_G3_Handguard_Base.BP_G3_Handguard_Base_C",
					G3_Plastic_stock = "/Game/ITR2/BPs/Items/Firearms/Primary/G3/G3_Parts/BP_G3_Plastic_stock.BP_G3_Plastic_stock_C",
				},

			},

			Remington700 = {
				R700_Mag_5 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/BP_R700_Mag_5.BP_R700_Mag_5_C",
				R700_Mag_10 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/BP_R700_Mag_10.BP_R700_Mag_10_C",
				R700_modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/BP_R700_modular_Base.BP_R700_modular_Base_C",
				R700_modular_S_var = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/BP_R700_modular_S_var.BP_R700_modular_S_var_C",

				Parts = {
					R700_ForeSight_Rail = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_ForeSight_Rail.BP_R700_ForeSight_Rail_C",
					R700_Foresight_Plank = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Foresight_Plank.BP_R700_Foresight_Plank_C",
					R700_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Barrel_Short.BP_R700_Barrel_Short_C",
					R700_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Barrel_Base.BP_R700_Barrel_Base_C",
					R700_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Barrel_Long.BP_R700_Barrel_Long_C",
					R700_LongStock_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_LongStock_1.BP_R700_LongStock_1_C",
					R700_LongStock_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_LongStock_2.BP_R700_LongStock_2_C",
					R700_LongStock_Handguard_P1 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_LongStock_Handguard_P1.BP_R700_LongStock_Handguard_P1_C",
					R700_StockAdapter_AR = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_StockAdapter_AR.BP_R700_StockAdapter_AR_C",
					R700_Stock = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Stock.BP_R700_Stock_C",
					R700_StockFolding = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_StockFolding.BP_R700_StockFolding_C",
					R700_Upper_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Upper_1.BP_R700_Upper_1_C",
					R700_Upper_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Upper_2.BP_R700_Upper_2_C",
					R700_Upper_3 = "/Game/ITR2/BPs/Items/Firearms/Primary/Remington700/Parts/BP_R700_Upper_3.BP_R700_Upper_3_C",
				},

			},

			IZh_27 = {
				Iz27_FullModular = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_FullModular.BP_Iz27_FullModular_C",
				Iz27_FullModular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_FullModular_S.BP_Iz27_FullModular_S_C",

				Iz27_Parts = {
					Rail_ShotgunDB_Middle = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Rail_ShotgunDB_Middle.BP_Rail_ShotgunDB_Middle_C",
					Rail_ShotgunDB_Underbarrel = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Rail_ShotgunDB_Underbarrel.BP_Rail_ShotgunDB_Underbarrel_C",
					Iz27_Handguard_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Handguard_Wood.BP_Iz27_Handguard_Wood_C",
					Iz27_Handguard_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Handguard_Plastic.BP_Iz27_Handguard_Plastic_C",
					Iz27_Stock_Handle_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Stock_Handle_Wood.BP_Iz27_Stock_Handle_Wood_C",
					Iz27_Handle_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Handle_Wood.BP_Iz27_Handle_Wood_C",
					Iz27_Stock_Handle_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Stock_Handle_Plastic.BP_Iz27_Stock_Handle_Plastic_C",
					Izh27_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Izh27_Barrel_Short.BP_Izh27_Barrel_Short_C",
					Izh27_Barrel_Short_S = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Izh27_Barrel_Short_S.BP_Izh27_Barrel_Short_S_C",
					Izh27_Barrel_Long2 = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Izh27_Barrel_Long2.BP_Izh27_Barrel_Long2_C",
				},

			},

			GP34 = {
				GP34_internal = "/Game/ITR2/BPs/Items/Firearms/Primary/GP34/BP_GP34_internal.BP_GP34_internal_C",
				GP34_attachment = "/Game/ITR2/BPs/Items/Firearms/Primary/GP34/BP_GP34_attachment.BP_GP34_attachment_C",
			},

			AK_Parts = {
				AK_Ak74_Handle_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Ak74_Handle_Basic.BP_AK_Ak74_Handle_Basic_C",
				AK_Ak74_Handle_Ergo1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Ak74_Handle_Ergo1.BP_AK_Ak74_Handle_Ergo1_C",
				AK_Ak74_Handle_Ergo2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Ak74_Handle_Ergo2.BP_AK_Ak74_Handle_Ergo2_C",
				Ak_AKM_Handle_Basic_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_Ak_AKM_Handle_Basic_1.BP_Ak_AKM_Handle_Basic_1_C",
				Ak_AKM_Handle_Basic_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_Ak_AKM_Handle_Basic_2.BP_Ak_AKM_Handle_Basic_2_C",
				AK_Saiga_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Saiga_Handle.BP_AK_Saiga_Handle_C",
				AK_Bizon_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Bizon_Handle.BP_AK_Bizon_Handle_C",
				AK_Vityaz_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Vityaz_Handle.BP_AK_Vityaz_Handle_C",
				AK_Kedr_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Kedr_Handle.BP_AK_Kedr_Handle_C",

				AK74_AKM_Parts = {
					Ak74_Handguard_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Handguard_Wood.BP_Ak74_Handguard_Wood_C",
					Ak74_Plastic_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Plastic_Black.BP_Ak74_Plastic_Black_C",
					Ak74_Handguard_Rail1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Handguard_Rail1.BP_Ak74_Handguard_Rail1_C",
					AK74_Akm_Handguard_Wood1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Akm_Handguard_Wood1.BP_AK74_Akm_Handguard_Wood1_C",
					AK74_Akm_Handguard_Wood2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Akm_Handguard_Wood2.BP_AK74_Akm_Handguard_Wood2_C",
					Ak74_Handguard_Dong = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Handguard_Dong.BP_Ak74_Handguard_Dong_C",
					Ak74_Stock_FoldingFrame = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_FoldingFrame.BP_Ak74_Stock_FoldingFrame_C",
					Ak74_Stock_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_Wood.BP_Ak74_Stock_Wood_C",
					AK74_AKM_Stock_Wood_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_AKM_Stock_Wood_1.BP_AK74_AKM_Stock_Wood_1_C",
					Ak74_Stock_Plug = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_Plug.BP_Ak74_Stock_Plug_C",
					Ak74_Stock_Plastic_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_Plastic_1.BP_Ak74_Stock_Plastic_1_C",
					Ak74_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Lid_Basic.BP_Ak74_Lid_Basic_C",
					Ak74_Lid_Rail1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Lid_Rail1.BP_Ak74_Lid_Rail1_C",
					AkM_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AkM_Lid_Basic.BP_AkM_Lid_Basic_C",
					AK74_Vityaz_Handguard_PL2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_PL2.BP_AK74_Vityaz_Handguard_PL2_C",
					AK74_Vityaz_Handguard_PL3 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_PL3.BP_AK74_Vityaz_Handguard_PL3_C",
					AK74_Vityaz_Handguard_Long_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_Long_Railed.BP_AK74_Vityaz_Handguard_Long_Railed_C",
					AK74_Vityaz_Handguard_Long_Railed_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_Long_Railed_2.BP_AK74_Vityaz_Handguard_Long_Railed_2_C",
					AK_StockAdapter_AKBS = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK_StockAdapter_AKBS.BP_AK_StockAdapter_AKBS_C",
					AK_StockAdapter_AR = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK_StockAdapter_AR.BP_AK_StockAdapter_AR_C",
				},

				AKSu_Bizon_Saiga_parts = {
					AkBS_Stock_Bizon_Folding = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Stock_Bizon_Folding.BP_AkBS_Stock_Bizon_Folding_C",
					AkBS_Stock_Saiga = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Stock_Saiga.BP_AkBS_Stock_Saiga_C",
					AkBS_Vityaz_Stock_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Vityaz_Stock_1.BP_AkBS_Vityaz_Stock_1_C",
					AkBS_Vityaz_Stock_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Vityaz_Stock_2.BP_AkBS_Vityaz_Stock_2_C",
					AkBS_Vityaz_Stock_3 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Vityaz_Stock_3.BP_AkBS_Vityaz_Stock_3_C",
					AkBS_Stock_Saiga_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Stock_Saiga_Wood.BP_AkBS_Stock_Saiga_Wood_C",
					AKBS_StockAdapter_AR_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AKBS_StockAdapter_AR_2.BP_AKBS_StockAdapter_AR_2_C",
				},

			},

			AR_Parts = {
				AR_SVD_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SVD_Handle.BP_AR_SVD_Handle_C",
				AR_SR25_Handle_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SR25_Handle_Base.BP_AR_SR25_Handle_Base_C",
				AR_M4A1_Handle_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_M4A1_Handle_Base.BP_AR_M4A1_Handle_Base_C",
				AR_Handle_Ergo_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_Handle_Ergo_1.BP_AR_Handle_Ergo_1_C",
				AR_Handle_Ergo_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_Handle_Ergo_2.BP_AR_Handle_Ergo_2_C",
				AR_SVD_Stock = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SVD_Stock.BP_AR_SVD_Stock_C",
				AR_M4A1_Stock_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_M4A1_Stock_1.BP_AR_M4A1_Stock_1_C",
				AR_M4A1_Stock_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_M4A1_Stock_2.BP_AR_M4A1_Stock_2_C",
				AR_SR_25_Stock = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SR-25_Stock.BP_AR_SR-25_Stock_C",
				AR_Light = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_Light.BP_AR_Light_C",
				AR_R700_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_R700_Handle.BP_AR_R700_Handle_C",
			},

		},

		Secondary = {

			PM = {
				Mag_PM = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_Mag_PM.BP_Mag_PM_C",
				Mag_PM_Long = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_Mag_PM_Long.BP_Mag_PM_Long_C",
				PM = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM.BP_PM_C",
				PM_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM_S.BP_PM_S_C",
				PM_mod = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM_mod.BP_PM_mod_C",
			},

			Gsh18 = {
				Mag_Gsh18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Mag_Gsh18.BP_Mag_Gsh18_C",
				Gsh18_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Gsh18_S.BP_Gsh18_S_C",
				Gsh18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Gsh18.BP_Gsh18_C",
			},

			Beretta = {
				Mag_Beretta = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Mag_Beretta.BP_Mag_Beretta_C",
				Beretta_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Beretta_S.BP_Beretta_S_C",
				Beretta = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Beretta.BP_Beretta_C",
			},

			Glock_18 = {
				Mag_Glock_18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Mag_Glock_18.BP_Mag_Glock_18_C",
				Mag_Glock_18_Long = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Mag_Glock_18_Long.BP_Mag_Glock_18_Long_C",
				Glock_18_s = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Glock_18_s.BP_Glock_18_s_C",
				Glock_18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Glock_18.BP_Glock_18_C",
			},

			FORT17 = {
				Mag_FORT17 = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_Mag_FORT17.BP_Mag_FORT17_C",
				FORT17_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_FORT17_S.BP_FORT17_S_C",
				FORT17_N = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_FORT17_N.BP_FORT17_N_C",
				FORT17_M = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_FORT17_M.BP_FORT17_M_C",
			},

			Colt1911 = {
				Mag_Colt = "/Game/ITR2/BPs/Items/Firearms/Secondary/Colt1911/BP_Mag_Colt.BP_Mag_Colt_C",
				Colt = "/Game/ITR2/BPs/Items/Firearms/Secondary/Colt1911/BP_Colt.BP_Colt_C",
				Colt_M = "/Game/ITR2/BPs/Items/Firearms/Secondary/Colt1911/BP_Colt_M.BP_Colt_M_C",
			},

			Colt1911_mini_9mm = {
				Mag_Colt_Mini = "/Game/ITR2/BPs/Items/Firearms/Secondary/Colt1911_mini_9mm/BP_Mag_Colt_Mini.BP_Mag_Colt_Mini_C",
				Colt_Mini = "/Game/ITR2/BPs/Items/Firearms/Secondary/Colt1911_mini_9mm/BP_Colt_Mini.BP_Colt_Mini_C",
			},

		},

		Attachments = {

			Scopes = {
				Scope_PSO = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_PSO.BP_Scope_PSO_C",
				RDS_Cobra = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_Cobra.BP_RDS_Cobra_C",
				RDS_PK6 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_PK6.BP_RDS_PK6_C",
				RDS_Dorris = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_Dorris.BP_RDS_Dorris_C",
				Scope_HG = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_HG.BP_Scope_HG_C",
				Scope_NF = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_NF.BP_Scope_NF_C",
				Scope_DorrisBig = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_DorrisBig.BP_Scope_DorrisBig_C",
				RDS_Red_Dot = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_Red_Dot.BP_RDS_Red_Dot_C",
				RDS_EODECK = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_EODECK.BP_RDS_EODECK_C",
				RDS_OKB71 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_OKB71.BP_RDS_OKB71_C",
				RDS_T4 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_T4.BP_RDS_T4_C",
				Scope_PU = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_PU.BP_Scope_PU_C",
				M4A1_Foresight = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_M4A1_Foresight.BP_M4A1_Foresight_C",
				M4A1_Celik = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_M4A1_Celik.BP_M4A1_Celik_C",
				Scope_Magnifier = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_Magnifier.BP_Scope_Magnifier_C",
				Scope_G36_Plank_with_Optic = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_G36_Plank_with_Optic.BP_Scope_G36_Plank_with_Optic_C",
				RDS_G36_Special = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_G36_Special.BP_RDS_G36_Special_C",
				Scope_Magnifier_L = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_Magnifier_L.BP_Scope_Magnifier_L_C",
				Benelli_Foresight_A1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Benelli_Foresight_A1.BP_Benelli_Foresight_A1_C",
				Benelli_Foresight_A2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Benelli_Foresight_A2.BP_Benelli_Foresight_A2_C",
				BenelliM2_RearSight = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_BenelliM2_RearSight.BP_BenelliM2_RearSight_C",
			},

			Rails = {
				Rail_45deg = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_45deg.BP_Rail_45deg_C",
				Rail_45deg_R = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_45deg_R.BP_Rail_45deg_R_C",
				Rail_PistolOverUnder = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_PistolOverUnder.BP_Rail_PistolOverUnder_C",
				Rail_Riser_A = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Riser_A.BP_Rail_Riser_A_C",
				DovetailToRail = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_DovetailToRail.BP_DovetailToRail_C",
				DovetailToRail_Low = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_DovetailToRail_Low.BP_DovetailToRail_Low_C",
				Rail_Plate_Medium_1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Medium_1.BP_Rail_Plate_Medium_1_C",
				Rail_Plate_Medium_2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Medium_2.BP_Rail_Plate_Medium_2_C",
				Rail_Plate_Short_1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Short_1.BP_Rail_Plate_Short_1_C",
				Rail_Plate_Short_2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Short_2.BP_Rail_Plate_Short_2_C",
				DovetailToRail_Vityaz = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_DovetailToRail_Vityaz.BP_DovetailToRail_Vityaz_C",
			},

			Illumination = {
				Att_Flashlight_small = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Flashlight_small.BP_Att_Flashlight_small_C",
				Att_Flashlight_Big = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Flashlight_Big.BP_Att_Flashlight_Big_C",
				PEQ15 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_PEQ15.BP_PEQ15_C",
				Att_Pointer_small_Red = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Pointer_small_Red.BP_Att_Pointer_small_Red_C",
				Att_Pointer_small_Blue = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Pointer_small_Blue.BP_Att_Pointer_small_Blue_C",
				Att_Pointer_small_Green = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Pointer_small_Green.BP_Att_Pointer_small_Green_C",
			},

			Muzzles = {

				AK = {
					MuzzleAK_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_Base.BP_MuzzleAK_Base_C",
					MuzzleAK_DTK2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_DTK2.BP_MuzzleAK_DTK2_C",
					MuzzleAK_DTK1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_DTK1.BP_MuzzleAK_DTK1_C",
					MuzzleAK_M11 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_M11.BP_MuzzleAK_M11_C",
					MuzzleAKSu_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAKSu_Base.BP_MuzzleAKSu_Base_C",
					MuzzleAKM_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAKM_Base.BP_MuzzleAKM_Base_C",
					MuzzleBizon_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleBizon_Base.BP_MuzzleBizon_Base_C",
				},

				M4A1 = {
					MuzzleM4A1_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/M4A1/BP_MuzzleM4A1_Base.BP_MuzzleM4A1_Base_C",
					MuzzleG36_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/M4A1/BP_MuzzleG36_Base.BP_MuzzleG36_Base_C",
				},

				Saiga = {
					Muzzle_Saiga = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/Saiga/BP_Muzzle_Saiga.BP_Muzzle_Saiga_C",
				},

				Vityaz = {
					MuzzleVityaz_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/Vityaz/BP_MuzzleVityaz_Base.BP_MuzzleVityaz_Base_C",
				},

				SR25 = {
					Muzzle_SR25_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/SR25/BP_Muzzle_SR25_Base.BP_Muzzle_SR25_Base_C",
				},

				R700 = {
					Muzzle_R700_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/R700/BP_Muzzle_R700_Base.BP_Muzzle_R700_Base_C",
				},

			},

			Silencers = {
				Silencer_Pistol = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_Pistol.BP_Silencer_Pistol_C",
				Silencer_5_45 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_5_45.BP_Silencer_5_45_C",
				Silencer_5_56 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_5_56.BP_Silencer_5_56_C",
				Silencer_7_62_54 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_7_62_54.BP_Silencer_7_62_54_C",
				Silencer_7_62_51 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_7_62_51.BP_Silencer_7_62_51_C",
				Silencer_MP9 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_MP9.BP_Silencer_MP9_C",
				Silencer_338 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_338.BP_Silencer_338_C",
			},

			AdditionalSlots = {
				Rail_ShotgunDB_Bandolier_4 = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_4.BP_Rail_ShotgunDB_Bandolier_4_C",
				Rail_ShotgunDB_Bandolier_8 = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_8.BP_Rail_ShotgunDB_Bandolier_8_C",
				Rail_ShotgunDB_Bandolier_Stock = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_Stock.BP_Rail_ShotgunDB_Bandolier_Stock_C",
				Rail_ShotgunDB_Bandolier_Stock_L = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_Stock_L.BP_Rail_ShotgunDB_Bandolier_Stock_L_C",
			},

			Grips = {

				Erco = {
					VertGrip_Erco_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Erco/BP_VertGrip_Erco_Black.BP_VertGrip_Erco_Black_C",
					VertGrip_Erco_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Erco/BP_VertGrip_Erco_Green_CH.BP_VertGrip_Erco_Green_CH_C",
					VertGrip_Erco_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Erco/BP_VertGrip_Erco_Orange_CH.BP_VertGrip_Erco_Orange_CH_C",
				},

				TungusUp = {
					VertGrip_TungusUp_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/TungusUp/BP_VertGrip_TungusUp_Black.BP_VertGrip_TungusUp_Black_C",
					VertGrip_TungusUp_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/TungusUp/BP_VertGrip_TungusUp_Green_CH.BP_VertGrip_TungusUp_Green_CH_C",
					VertGrip_TungusUp_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/TungusUp/BP_VertGrip_TungusUp_Orange_CH.BP_VertGrip_TungusUp_Orange_CH_C",
				},

				Mokpick = {
					VertGrip_MockPick_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Mokpick/BP_VertGrip_MockPick_Black.BP_VertGrip_MockPick_Black_C",
					VertGrip_MockPick_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Mokpick/BP_VertGrip_MockPick_Green_CH.BP_VertGrip_MockPick_Green_CH_C",
					VertGrip_MockPick_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Mokpick/BP_VertGrip_MockPick_Orange_CH.BP_VertGrip_MockPick_Orange_CH_C",
				},

				Gobar = {
					VertGrip_Gobar_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Gobar/BP_VertGrip_Gobar_Black.BP_VertGrip_Gobar_Black_C",
					VertGrip_Gobar_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Gobar/BP_VertGrip_Gobar_Green_CH.BP_VertGrip_Gobar_Green_CH_C",
					VertGrip_Gobar_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Gobar/BP_VertGrip_Gobar_Orange_CH.BP_VertGrip_Gobar_Orange_CH_C",
				},

			},

			Bipod = {
				Bipod_MgPul = "/Game/ITR2/BPs/Items/Firearms/Attachments/Bipod/BP_Bipod_MgPul.BP_Bipod_MgPul_C",
			},

		},

	},

	Ammo = {

		AmmoBox = {
			AmmoBox_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_FMJ.BP_AmmoBox_9x18_FMJ_C",
			AmmoBox_9x18_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_Tracer.BP_AmmoBox_9x18_Tracer_C",
			AmmoBox_9x18_PlusP = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_PlusP.BP_AmmoBox_9x18_PlusP_C",
			AmmoBox_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x19_FMJ.BP_AmmoBox_9x19_FMJ_C",
			AmmoBox_9x19_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x19_Tracer.BP_AmmoBox_9x19_Tracer_C",
			AmmoBox_12x70_BuckShot = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_BuckShot.BP_AmmoBox_12x70_BuckShot_C",
			AmmoBox_12x70_Slug = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_Slug.BP_AmmoBox_12x70_Slug_C",
			AmmoBox_12x70_SlugTracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_SlugTracer.BP_AmmoBox_12x70_SlugTracer_C",
			AmmoBox_545x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_FMJ.BP_AmmoBox_545x39_FMJ_C",
			AmmoBox_545x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_Tracer.BP_AmmoBox_545x39_Tracer_C",
			AmmoBox_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_5-56x45_FMJ.BP_AmmoBox_5-56x45_FMJ_C",
			AmmoBox_5_56x45_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_5-56x45_Tracer.BP_AmmoBox_5-56x45_Tracer_C",
			AmmoBox_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x39_FMJ.BP_AmmoBox_7-62x39_FMJ_C",
			AmmoBox_7_62x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x39_Tracer.BP_AmmoBox_7-62x39_Tracer_C",
			AmmoBox_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x51_FMJ.BP_AmmoBox_7-62x51_FMJ_C",
			AmmoBox_7_62x51_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x51_Tracer.BP_AmmoBox_7-62x51_Tracer_C",
			AmmoBox_7_62x54R_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x54R_FMJ.BP_AmmoBox_7-62x54R_FMJ_C",
			AmmoBox_7_62x54R_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x54R_Tracer.BP_AmmoBox_7-62x54R_Tracer_C",
			AmmoBox_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x39_FMJ.BP_AmmoBox_9x39_FMJ_C",
			AmmoBox_9x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x39_Tracer.BP_AmmoBox_9x39_Tracer_C",
			AmmoBox_545x39_BP = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_BP.BP_AmmoBox_545x39_BP_C",
			AmmoBox_45ACP_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_45ACP_FMJ.BP_AmmoBox_45ACP_FMJ_C",
			AmmoBox_45ACP_TR = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_45ACP_TR.BP_AmmoBox_45ACP_TR_C",
			AmmoBox_338Magnum = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_338Magnum.BP_AmmoBox_338Magnum_C",
			AmmoBox_338Magnum_TR = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_338Magnum_TR.BP_AmmoBox_338Magnum_TR_C",
		},

		LargeAmmoBox = {
			AmmoBoxLarge_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x18_FMJ.BP_AmmoBoxLarge_9x18_FMJ_C",
			AmmoBoxLarge_9x18_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x18_TR.BP_AmmoBoxLarge_9x18_TR_C",
			AmmoBoxLarge_9x18_PlusP = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x18_PlusP.BP_AmmoBoxLarge_9x18_PlusP_C",
			AmmoBoxLarge_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x19_FMJ.BP_AmmoBoxLarge_9x19_FMJ_C",
			AmmoBoxLarge_9x19_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x19_TR.BP_AmmoBoxLarge_9x19_TR_C",
			AmmoBoxLarge_12x70_BuckShot = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_BuckShot.BP_AmmoBoxLarge_12x70_BuckShot_C",
			AmmoBoxLarge_12x70_Slug = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_Slug.BP_AmmoBoxLarge_12x70_Slug_C",
			AmmoBoxLarge_12x70_SlugTR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_SlugTR.BP_AmmoBoxLarge_12x70_SlugTR_C",
			AmmoBoxLarge_5_45x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_45x39_FMJ.BP_AmmoBoxLarge_5_45x39_FMJ_C",
			AmmoBoxLarge_5_45x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_45x39_TR.BP_AmmoBoxLarge_5_45x39_TR_C",
			AmmoBoxLarge_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_56x45_FMJ.BP_AmmoBoxLarge_5_56x45_FMJ_C",
			AmmoBoxLarge_5_56x45_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_56x45_TR.BP_AmmoBoxLarge_5_56x45_TR_C",
			AmmoBoxLarge_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x39_FMJ.BP_AmmoBoxLarge_7_62x39_FMJ_C",
			AmmoBoxLarge_7_62x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x39_TR.BP_AmmoBoxLarge_7_62x39_TR_C",
			AmmoBoxLarge_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x51_FMJ.BP_AmmoBoxLarge_7_62x51_FMJ_C",
			AmmoBoxLarge_7_62x51_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x51_TR.BP_AmmoBoxLarge_7_62x51_TR_C",
			AmmoBoxLarge_7_62x54_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x54_FMJ.BP_AmmoBoxLarge_7_62x54_FMJ_C",
			AmmoBoxLarge_7_62x54_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x54_TR.BP_AmmoBoxLarge_7_62x54_TR_C",
			AmmoBoxLarge_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x39_FMJ.BP_AmmoBoxLarge_9x39_FMJ_C",
			AmmoBoxLarge_9x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x39_TR.BP_AmmoBoxLarge_9x39_TR_C",
			AmmoBoxLarge_45ACP_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_45ACP_FMJ.BP_AmmoBoxLarge_45ACP_FMJ_C",
			AmmoBoxLarge_45ACP_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_45ACP_TR.BP_AmmoBoxLarge_45ACP_TR_C",
			AmmoBoxLarge_338_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_338_FMJ.BP_AmmoBoxLarge_338_FMJ_C",
			AmmoBoxLarge_338_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_338_TR.BP_AmmoBoxLarge_338_TR_C",
		},

		Cartridges = {
			_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_FMJ.BP_9x18_FMJ_C",
			_9x18_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_TR.BP_9x18_TR_C",
			_9x18_PlusP = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_PlusP.BP_9x18_PlusP_C",
			_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x19_FMJ.BP_9x19_FMJ_C",
			_9x19_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x19_TR.BP_9x19_TR_C",
			_12g_Buckshot = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_Buckshot.BP_12g_Buckshot_C",
			_12g_Slug = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_Slug.BP_12g_Slug_C",
			_12g_SlugTracer = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_SlugTracer.BP_12g_SlugTracer_C",
			_5_45x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_FMJ.BP_5-45x39_FMJ_C",
			_5_45x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_TR.BP_5-45x39_TR_C",
			_5_45x39_BP = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_BP.BP_5-45x39_BP_C",
			_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-56x45_FMJ.BP_5-56x45_FMJ_C",
			_5_56x45_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-56x45_TR.BP_5-56x45_TR_C",
			_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x39_FMJ.BP_7-62x39_FMJ_C",
			_7_62x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x39_TR.BP_7-62x39_TR_C",
			_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x51_FMJ.BP_7-62x51_FMJ_C",
			_7_62x51_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x51_TR.BP_7-62x51_TR_C",
			_7_62x54R_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x54R_FMJ.BP_7-62x54R_FMJ_C",
			_7_62x54R_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x54R_TR.BP_7-62x54R_TR_C",
			_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x39_FMJ.BP_9x39_FMJ_C",
			_9x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x39_TR.BP_9x39_TR_C",
			VOG = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_VOG.BP_VOG_C",
			_45ACP_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_45ACP_FMJ.BP_45ACP_FMJ_C",
			_45ACP_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_45ACP_TR.BP_45ACP_TR_C",
			_338_LAPUA_MAGNUM = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_338_LAPUA_MAGNUM.BP_338_LAPUA_MAGNUM_C",
			_338_LAPUA_MAGNUM_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_338_LAPUA_MAGNUM_TR.BP_338_LAPUA_MAGNUM_TR_C",
		},

	},

	Consumable = {
		CigPack = "/Game/ITR2/BPs/Items/Consumable/BP_CigPack.BP_CigPack_C",
		Cig = "/Game/ITR2/BPs/Items/Consumable/BP_Cig.BP_Cig_C",
		Injector_QuickHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_QuickHeal.BP_Injector_QuickHeal_C",
		Injector_SlowHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_SlowHeal.BP_Injector_SlowHeal_C",
		Injector_FullHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_FullHeal.BP_Injector_FullHeal_C",
		Chocolate = "/Game/ITR2/BPs/Items/Consumable/BP_Chocolate.BP_Chocolate_C",
		FoodContainer_Fish = "/Game/ITR2/BPs/Items/Consumable/BP_FoodContainer_Fish.BP_FoodContainer_Fish_C",
		FoodContainer_Meat = "/Game/ITR2/BPs/Items/Consumable/BP_FoodContainer_Meat.BP_FoodContainer_Meat_C",
		FoodContainer_PineApples = "/Game/ITR2/BPs/Items/Consumable/BP_FoodContainer_PineApples.BP_FoodContainer_PineApples_C",
		Food_Meat_1 = "/Game/ITR2/BPs/Items/Consumable/BP_Food_Meat_1.BP_Food_Meat_1_C",
		Food_Meat_2 = "/Game/ITR2/BPs/Items/Consumable/BP_Food_Meat_2.BP_Food_Meat_2_C",
		Food_Meat_3 = "/Game/ITR2/BPs/Items/Consumable/BP_Food_Meat_3.BP_Food_Meat_3_C",
		Food_PineApple = "/Game/ITR2/BPs/Items/Consumable/BP_Food_PineApple.BP_Food_PineApple_C",
		Cracker = "/Game/ITR2/BPs/Items/Consumable/BP_Cracker.BP_Cracker_C",
		CanFish = "/Game/ITR2/BPs/Items/Consumable/BP_CanFish.BP_CanFish_C",
		CrackerPack = "/Game/ITR2/BPs/Items/Consumable/BP_CrackerPack.BP_CrackerPack_C",
	},

	Misc = {
		Lighter = "/Game/ITR2/BPs/Items/Misc/BP_Lighter.BP_Lighter_C",
		Basketball_ball = "/Game/ITR2/BPs/Items/Misc/BP_Basketball_ball.BP_Basketball_Ball_C",
		CassettePlayer = "/Game/ITR2/BPs/Items/Misc/BP_CassettePlayer.BP_CassettePlayer_C",
		Misc_Item_Bucket_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Bucket_1.BP_Misc_Item_Bucket_1_C",
		Misc_Item_CupFotTea = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_CupFotTea.BP_Misc_Item_CupFotTea_C",
		Misc_Item_Mug = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Mug.BP_Misc_Item_Mug_C",
		Misc_Item_CarpetBeater = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_CarpetBeater.BP_Misc_Item_CarpetBeater_C",
		Misc_Item_Pan_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Pan_1.BP_Misc_Item_Pan_1_C",
		Misc_Item_Pan_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Pan_2.BP_Misc_Item_Pan_2_C",
		Misc_Item_Plate = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Plate.BP_Misc_Item_Plate_C",
		Misc_Item_Can_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Can_1.BP_Misc_Item_Can_1_C",
		Misc_Item_Padlock = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Padlock.BP_Misc_Item_Padlock_C",
		Misc_Item_Soap = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Soap.BP_Misc_Item_Soap_C",
		Misc_Item_Spoon = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Spoon.BP_Misc_Item_Spoon_C",
		Misc_Item_ToyCube = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube.BP_Misc_Item_ToyCube_C",
		Misc_Item_Wrench = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Wrench.BP_Misc_Item_Wrench_C",
		Misc_Item_Mug2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Mug2.BP_Misc_Item_Mug2_C",
		Misc_Item_Mug3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Mug3.BP_Misc_Item_Mug3_C",
		Misc_Item_Nevalashka = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Nevalashka.BP_Misc_Item_Nevalashka_C",
		Misc_Item_Teddy = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Teddy.BP_Misc_Item_Teddy_C",
		Misc_Item_Radio = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Radio.BP_Misc_Item_Radio_C",
		Misc_Item_Toy_Gun_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Toy_Gun_1.BP_Misc_Item_Toy_Gun_1_C",
		Misc_Item_Toy_Gun_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Toy_Gun_2.BP_Misc_Item_Toy_Gun_2_C",
		Misc_Item_Toy_Gun_3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Toy_Gun_3.BP_Misc_Item_Toy_Gun_3_C",
		Misc_Item_Phone = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Phone.BP_Misc_Item_Phone_C",
		Misc_Item_ToyCube_CH_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_1.BP_Misc_Item_ToyCube_CH_1_C",
		Misc_Item_ToyCube_CH_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_2.BP_Misc_Item_ToyCube_CH_2_C",
		Misc_Item_ToyCube_CH_3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_3.BP_Misc_Item_ToyCube_CH_3_C",
		Misc_Item_ToyCube_CH_4 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_4.BP_Misc_Item_ToyCube_CH_4_C",
		Misc_Item_ToyCube_CH_5 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_5.BP_Misc_Item_ToyCube_CH_5_C",
		Misc_Item_ToyCube_CH_6 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_6.BP_Misc_Item_ToyCube_CH_6_C",
		Misc_Item_Rubick = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Rubick.BP_Misc_Item_Rubick_C",
		Misc_Toy_Truck_Full = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Toy_Truck_Full.BP_Misc_Toy_Truck_Full_C",
		Misc_Clock = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Clock.BP_Misc_Clock_C",
		Misc_Item_Electro = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Electro.BP_Misc_Item_Electro_C",
		Misc_Item_Rasp_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Rasp_1.BP_Misc_Item_Rasp_1_C",
		Misc_Item_Rasp_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Rasp_2.BP_Misc_Item_Rasp_2_C",
		Misc_Item_Wrench_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Wrench_2.BP_Misc_Item_Wrench_2_C",
		Misc_Item_Screw_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Screw_1.BP_Misc_Item_Screw_1_C",
		Misc_Item_Screw_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Screw_2.BP_Misc_Item_Screw_2_C",
		Misc_Item_Screw_3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Screw_3.BP_Misc_Item_Screw_3_C",
		Misc_Item_Screw_4 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Screw_4.BP_Misc_Item_Screw_4_C",
		Misc_Item_Pliers_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Pliers_1.BP_Misc_Item_Pliers_1_C",
		Misc_Item_Pliers_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Pliers_2.BP_Misc_Item_Pliers_2_C",
		Misc_Item_Clamp = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Clamp.BP_Misc_Item_Clamp_C",
		Misc_Item_Book_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_1.BP_Misc_Item_Book_1_C",
		Misc_Item_Book_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_2.BP_Misc_Item_Book_2_C",
		Misc_Item_Book_3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_3.BP_Misc_Item_Book_3_C",
		Misc_Item_Book_4 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_4.BP_Misc_Item_Book_4_C",
		Misc_Item_Book_5 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_5.BP_Misc_Item_Book_5_C",
		Misc_Item_Book_6 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_6.BP_Misc_Item_Book_6_C",
		Misc_Item_Book_7 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_7.BP_Misc_Item_Book_7_C",
		Misc_Item_Book_8 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_8.BP_Misc_Item_Book_8_C",
		Misc_Item_Book_9 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_9.BP_Misc_Item_Book_9_C",
		Misc_Item_Book_10 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Book_10.BP_Misc_Item_Book_10_C",
		Misc_Item_Kettle_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Kettle_1.BP_Misc_Item_Kettle_1_C",
		Misc_Item_Kettle_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Kettle_2.BP_Misc_Item_Kettle_2_C",
		Misc_Item_Bulb = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Bulb.BP_Misc_Item_Bulb_C",
		Misc_Item_Sponge = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Sponge.BP_Misc_Item_Sponge_C",
		Misc_Item_T_Paper = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_T_Paper.BP_Misc_Item_T_Paper_C",
		Misc_Item_Barbell = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Barbell.BP_Misc_Item_Barbell_C",
		Misc_Item_Canister = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Canister.BP_Misc_Item_Canister_C",
		Misc_Item_Watch_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Watch_1.BP_Misc_Item_Watch_1_C",
		Misc_Item_Watch_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Watch_2.BP_Misc_Item_Watch_2_C",
		Misc_Item_Wrench_3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Wrench_3.BP_Misc_Item_Wrench_3_C",
		Misc_Item_Wrench_4 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Wrench_4.BP_Misc_Item_Wrench_4_C",
		Misc_Item_Hanger_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Hanger_1.BP_Misc_Item_Hanger_1_C",
		Misc_Item_Hanger_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Hanger_2.BP_Misc_Item_Hanger_2_C",
		Misc_Item_ForkSpoon = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ForkSpoon.BP_Misc_Item_ForkSpoon_C",

		CheckersBoardGame = {
			BlackCheckersPack = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_BlackCheckersPack.BP_BlackCheckersPack_C",
			WhiteCheckersPack = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_WhiteCheckersPack.BP_WhiteCheckersPack_C",
			Checker_White_Item_New = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Checker_White_Item_New.BP_Checker_White_Item_New_C",
			Checker_Black_Item_New = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Checker_Black_Item_New.BP_Checker_Black_Item_New_C",
			Dice = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Dice.BP_Dice_C",
			Dice_Glass = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Dice_Glass.BP_Dice_Glass_C",
		},

		Guitar = {
			Coin = "/Game/ITR2/BPs/Items/Misc/Guitar/BP_Coin.BP_Coin_C",
			Guitar = "/Game/ITR2/BPs/Items/Misc/Guitar/BP_Guitar.BP_Guitar_C",
		},

		AnniversaryItems = {
			Misc_Item_Toy_PechoAngry = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_Toy_PechoAngry.BP_Misc_Item_Toy_PechoAngry_C",
			Misc_Item_Toy_PechoLoving = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_Toy_PechoLoving.BP_Misc_Item_Toy_PechoLoving_C",
			Misc_Item_Toy_PechoQuiet = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_Toy_PechoQuiet.BP_Misc_Item_Toy_PechoQuiet_C",
			Misc_Item_AnniversaryCertificate = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_AnniversaryCertificate.BP_Misc_Item_AnniversaryCertificate_C",
			Misc_Item_MugAnniversary = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_MugAnniversary.BP_Misc_Item_MugAnniversary_C",
		},

		ShelfBoxes = {
			BoxForShelf_1 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_BoxForShelf_1.BP_BoxForShelf_1_C",
			BoxForShelf_2 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_BoxForShelf_2.BP_BoxForShelf_2_C",
			ShelfBox_LargeAmmo_3 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_LargeAmmo_3.BP_ShelfBox_LargeAmmo_3_C",
			ShelfBox_LargeAmmo_3_2 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_LargeAmmo_3_2.BP_ShelfBox_LargeAmmo_3_2_C",
			ShelfBox_LargeAmmo_6 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_LargeAmmo_6.BP_ShelfBox_LargeAmmo_6_C",
			ShelfBox_SmallAmmo_1 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_SmallAmmo_1.BP_ShelfBox_SmallAmmo_1_C",
			ShelfBox_SmallAmmo_t2 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_SmallAmmo_t2.BP_ShelfBox_SmallAmmo_t2_C",
			ShelfBox_Plates = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_Plates.BP_ShelfBox_Plates_C",
			BoxForShelf_Weapon = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_BoxForShelf_Weapon.BP_BoxForShelf_Weapon_C",
			ShelfBox_SmallContainer = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_SmallContainer.BP_ShelfBox_SmallContainer_C",
		},

		Notes = {
			Note_Basic = "/Game/ITR2/BPs/Misc/Notes/BP_Note_Basic.BP_Note_Basic_C",
			Note_Small = "/Game/ITR2/BPs/Misc/Notes/BP_Note_Small.BP_Note_Small_C",

			ItemInstruction = {
				Note_ArtifactDetector_lvl1 = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_ArtifactDetector_lvl1.BP_Note_ArtifactDetector_lvl1_C",
				Note_ArtifactDetector_lvl2 = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_ArtifactDetector_lvl2.BP_Note_ArtifactDetector_lvl2_C",
				Note_ArtifactContainerPrototype = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_ArtifactContainerPrototype.BP_Note_ArtifactContainerPrototype_C",
				Note_Battery = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_Battery.BP_Note_Battery_C",
				Note_DPH_Prototype = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_DPH_Prototype.BP_Note_DPH_Prototype_C",
				Note_Throwsonde_Prototype = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_Throwsonde_Prototype.BP_Note_Throwsonde_Prototype_C",
				Note_Tripod = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_Tripod.BP_Note_Tripod_C",
				Note_Tripod_Distortion = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_Tripod_Distortion.BP_Note_Tripod_Distortion_C",
				Note_Valuables = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_Valuables.BP_Note_Valuables_C",
				Note_TED = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_TED.BP_Note_TED_C",
				Note_RatCase = "/Game/ITR2/BPs/Misc/Notes/ItemInstruction/BP_Note_RatCase.BP_Note_RatCase_C",
			},

		},

		FinalChoice = {
			Art_Mission_GoldSphere = "/Game/ITR2/BPs/Misc/FinalChoice/BP_Art_Mission_GoldSphere.BP_Art_Mission_GoldSphere_C",
			GoldenSphereControl = "/Game/ITR2/BPs/Misc/FinalChoice/BP_GoldenSphereControl.BP_GoldenSphereControl_C",
		},

	},

	Artefacts = {
		Detector = "/Game/ITR2/BPs/Items/Artefacts/BP_Detector.BP_Detector_C",
		Detector_Lvl2 = "/Game/ITR2/BPs/Items/Artefacts/BP_Detector_Lvl2.BP_Detector_Lvl2_C",

		Nests = {
			StickyNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_StickyNest.BP_StickyNest_C",
			FragileNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_FragileNest.BP_FragileNest_C",
			MirrorShardsNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_MirrorShardsNest.BP_MirrorShardsNest_C",
			InvisibleNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_InvisibleNest.BP_InvisibleNest_C",
		},

		Arts = {

			MissionsArts = {
				Art_Mission_Cube = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission_Cube.BP_Art_Mission_Cube_C",
				Art_Mission_Lock = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission_Lock.BP_Art_Mission_Lock_C",
				Art_Mission_Rubick = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission_Rubick.BP_Art_Mission_Rubick_C",
				Art_Mission_Bulb = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission_Bulb.BP_Art_Mission_Bulb_C",
				Art_Mission_Nevalashka = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission_Nevalashka.BP_Art_Mission_Nevalashka_C",
				Art_Door = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Door.BP_Art_Door_C",
				Art_Mission_Nevalashka_2 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission_Nevalashka_2.BP_Art_Mission_Nevalashka_2_C",
			},

		},

	},

	Flashlights = {
		Flashlight_Handheld = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_Handheld.BP_Flashlight_Handheld_C",
		Flashlight_Pocket = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_Pocket.BP_Flashlight_Pocket_C",
		Flashlight_HeadLamp = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_HeadLamp.BP_Flashlight_HeadLamp_C",
	},

	Equipment = {

		Helmets = {
			Helmet_SSH_94 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_SSH_94.BP_Helmet_SSH_94_C",
			Helmet_Pasgt = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_Pasgt.BP_Helmet_Pasgt_C",
			Helmet_Pasgt_NVG = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_Pasgt_NVG.BP_Helmet_Pasgt_NVG_C",
			Helmet_FAST = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_FAST.BP_Helmet_FAST_C",
			NVG_Harness = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_NVG_Harness.BP_NVG_Harness_C",
			Hat_1 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Hat_1.BP_Hat_1_C",
			Hat_2 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Hat_2.BP_Hat_2_C",
			Hat_3 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Hat_3.BP_Hat_3_C",
			Hat_4 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Hat_4.BP_Hat_4_C",
			Hat_5 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Hat_5.BP_Hat_5_C",
			Hat_6 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Hat_6.BP_Hat_6_C",

			Helmet_Attachments = {
				Armored_Visor = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_Armored_Visor.BP_Armored_Visor_C",
				NV_JArm = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_NV_JArm.BP_NV_JArm_C",
				NV_Mount = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_NV_Mount.BP_NV_Mount_C",
				PVS14 = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_PVS14.BP_PVS14_C",
				PVS7 = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_PVS7.BP_PVS7_C",
				PVS31 = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_PVS31.BP_PVS31_C",
				GPNVG = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_GPNVG.BP_GPNVG_C",
			},

		},

		Tablet = {
			Tablet = "/Game/ITR2/BPs/Items/Equipment/Tablet/BP_Tablet.BP_Tablet_C",
		},

		Armors = {
			ArmorPlate_Light = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Light.BP_ArmorPlate_Light_C",
			ArmorPlate_Medium = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Medium.BP_ArmorPlate_Medium_C",
			ArmorPlate_Heavy = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Heavy.BP_ArmorPlate_Heavy_C",
			Armor_Modular_Light_Sand = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Light_Sand.BP_Armor_Modular_Light_Sand_C",
			Armor_Modular_Heavy_Sand = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Heavy_Sand.BP_Armor_Modular_Heavy_Sand_C",
		},

		Anti_Distortion_Helmets = {
			ADH_1 = "/Game/ITR2/BPs/Items/Equipment/Anti_Distortion_Helmets/BP_ADH_1.BP_ADH_1_C",
			ADH_1_Prototype = "/Game/ITR2/BPs/Items/Equipment/Anti_Distortion_Helmets/BP_ADH_1_Prototype.BP_ADH_1_Prototype_C",
		},

		Modules = {
			Module_ItemSlot = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemSlot.BP_Module_ItemSlot_C",
			Module_HelmetHook = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_HelmetHook.BP_Module_HelmetHook_C",
			Module_ItemPatch_UNPSC = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC.BP_Module_ItemPatch_UNPSC_C",
			Module_ItemPatch_ITR1_Red = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_ITR1_Red.BP_Module_ItemPatch_ITR1_Red_C",
			Module_TabletPocket = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_TabletPocket.BP_Module_TabletPocket_C",
			Module_ItemPatch_UNPSC_AL1 = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC_AL1.BP_Module_ItemPatch_UNPSC_AL1_C",
			Module_ItemPatch_UNPSC_AL2 = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC_AL2.BP_Module_ItemPatch_UNPSC_AL2_C",
			Module_ItemPatch_UNPSC_AL3 = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC_AL3.BP_Module_ItemPatch_UNPSC_AL3_C",
			Module_ItemPatch_UNPSC_AL4 = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC_AL4.BP_Module_ItemPatch_UNPSC_AL4_C",
			Module_ItemPatch_UNPSC_AL5 = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC_AL5.BP_Module_ItemPatch_UNPSC_AL5_C",
			Module_ItemPatch_UNPSC_AL6 = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC_AL6.BP_Module_ItemPatch_UNPSC_AL6_C",
			Module_ItemPatch_UNPSC_AL7 = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC_AL7.BP_Module_ItemPatch_UNPSC_AL7_C",

			Sand = {
				Module_DropPouch_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_DropPouch_Sand.BP_Module_DropPouch_Sand_C",
				Module_MagPouch_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouch_Sand.BP_Module_MagPouch_Sand_C",
				Module_MagPouch_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouch_NoMolle_Sand.BP_Module_MagPouch_NoMolle_Sand_C",
				Module_HolsterPistol_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_L_Sand.BP_Module_HolsterPistol_L_Sand_C",
				Module_HolsterPistol_L_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_L_NoMolle_Sand.BP_Module_HolsterPistol_L_NoMolle_Sand_C",
				Module_HolsterPistol_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_R_Sand.BP_Module_HolsterPistol_R_Sand_C",
				Module_HolsterPistol_R_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_R_NoMolle_Sand.BP_Module_HolsterPistol_R_NoMolle_Sand_C",
				Module_HolsterRifle_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_L_Sand.BP_Module_HolsterRifle_L_Sand_C",
				Module_HolsterRifle_L_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_L_NoMolle_Sand.BP_Module_HolsterRifle_L_NoMolle_Sand_C",
				Module_HolsterRifle_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_R_Sand.BP_Module_HolsterRifle_R_Sand_C",
				Module_HolsterRifle_R_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_R_NoMolle_Sand.BP_Module_HolsterRifle_R_NoMolle_Sand_C",
				Module_AmmoPouch_12_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_12_Sand.BP_Module_AmmoPouch_12_Sand_C",
				Module_AmmoPouch_8_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_8_Sand.BP_Module_AmmoPouch_8_Sand_C",
				Module_AmmoPouch_6_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_6_Sand.BP_Module_AmmoPouch_6_Sand_C",
				Module_AmmoPouch_4_1_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_4_1_Sand.BP_Module_AmmoPouch_4_1_Sand_C",
				Module_AmmoPouch_4_2_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_4_2_Sand.BP_Module_AmmoPouch_4_2_Sand_C",
				Module_AmmoBoxPouch_Vertical_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Vertical_L_Sand.BP_Module_AmmoBoxPouch_Vertical_L_Sand_C",
				Module_AmmoBoxPouch_Vertical_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Vertical_R_Sand.BP_Module_AmmoBoxPouch_Vertical_R_Sand_C",
				Module_AmmoBoxPouch_Horizontal_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Horizontal_R_Sand.BP_Module_AmmoBoxPouch_Horizontal_R_Sand_C",
				Module_AmmoBoxPouch_Horizontal_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Horizontal_L_Sand.BP_Module_AmmoBoxPouch_Horizontal_L_Sand_C",
				Module_MagPouchPistol_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouchPistol_Sand.BP_Module_MagPouchPistol_Sand_C",
				Module_MagPouchPistol_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouchPistol_NoMolle_Sand.BP_Module_MagPouchPistol_NoMolle_Sand_C",
			},

		},

		Vests = {
			Vest_Modular_Sand = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Modular_Sand.BP_Vest_Modular_Sand_C",
		},

		Backpacks = {
			BackPack_Small_Modular_Sand = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Small_Modular_Sand.BP_BackPack_Small_Modular_Sand_C",
			BackPack_Medium_Modular_Sand = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Medium_Modular_Sand.BP_BackPack_Medium_Modular_Sand_C",
		},

	},

	Valuables = {
		ValuableItem_Cup = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Cup.BP_ValuableItem_Cup_C",
		ValuableItem_Sugar = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Sugar.BP_ValuableItem_Sugar_C",
		ValuableItem_Wrench = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Wrench.BP_ValuableItem_Wrench_C",
		ValuableItem_Soap = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Soap.BP_ValuableItem_Soap_C",
		ValuableItem_Spoon = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Spoon.BP_ValuableItem_Spoon_C",
		ValuableItem_CubeToy = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_CubeToy.BP_ValuableItem_CubeToy_C",
		ValuableItem_Lock = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Lock.BP_ValuableItem_Lock_C",
		ValuableItem_Nevalashka = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Nevalashka.BP_ValuableItem_Nevalashka_C",
		ValuableItem_Rubick = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Rubick.BP_ValuableItem_Rubick_C",
		ValuableItem_Brush = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Brush.BP_ValuableItem_Brush_C",
		ValuableItem_alarm_Clock = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_alarm_Clock.BP_ValuableItem_alarm_Clock_C",
		ValuableItem_Bulb = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Bulb.BP_ValuableItem_Bulb_C",
		ValuableItem_Plate_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Plate_1.BP_ValuableItem_Plate_1_C",
		ValuableItem_Toy_Gun_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Toy_Gun_1.BP_ValuableItem_Toy_Gun_1_C",
		ValuableItem_Toy_Gun_2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Toy_Gun_2.BP_ValuableItem_Toy_Gun_2_C",
		ValuableItem_Toy_Gun_3 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Toy_Gun_3.BP_ValuableItem_Toy_Gun_3_C",
		ValuableItem_Bear = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Bear.BP_ValuableItem_Bear_C",
		ValuableItem_Phone = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Phone.BP_ValuableItem_Phone_C",
		ValuableItem_Cube_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Cube_1.BP_ValuableItem_Cube_1_C",
		ValuableItem_Cup_v2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Cup_v2.BP_ValuableItem_Cup_v2_C",
		ValuableItem_Kettle_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Kettle_1.BP_ValuableItem_Kettle_1_C",
		ValuableItem_Kettle_2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Kettle_2.BP_ValuableItem_Kettle_2_C",
		ValuableItem_Cup_v3 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Cup_v3.BP_ValuableItem_Cup_v3_C",
		ValuableItem_Book_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Book_1.BP_ValuableItem_Book_1_C",
		ValuableItem_Book_2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Book_2.BP_ValuableItem_Book_2_C",
		ValuableItem_Book_3 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Book_3.BP_ValuableItem_Book_3_C",
		ValuableItem_Book_4 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Book_4.BP_ValuableItem_Book_4_C",
		ValuableItem_Book_5 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Book_5.BP_ValuableItem_Book_5_C",
		ValuableItem_Calendar = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Calendar.BP_ValuableItem_Calendar_C",
		ValuableItem_Watch_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Watch_1.BP_ValuableItem_Watch_1_C",
		ValuableItem_asher = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_asher.BP_ValuableItem_asher_C",
		ValuableItem_Sponge = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Sponge.BP_ValuableItem_Sponge_C",
		ValuableItem_Electro = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Electro.BP_ValuableItem_Electro_C",
		ValuableItem_Rasp_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Rasp_1.BP_ValuableItem_Rasp_1_C",
		ValuableItem_Rasp_2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Rasp_2.BP_ValuableItem_Rasp_2_C",
		ValuableItem_Wrench_2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Wrench_2.BP_ValuableItem_Wrench_2_C",
		ValuableItem_Screw_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Screw_1.BP_ValuableItem_Screw_1_C",
		ValuableItem_Screw_2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Screw_2.BP_ValuableItem_Screw_2_C",
		ValuableItem_Screw_3 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Screw_3.BP_ValuableItem_Screw_3_C",
		ValuableItem_Screw_4 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Screw_4.BP_ValuableItem_Screw_4_C",
		ValuableItem_Pliers_1 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Pliers_1.BP_ValuableItem_Pliers_1_C",
		ValuableItem_Pliers_2 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Pliers_2.BP_ValuableItem_Pliers_2_C",
		ValuableItem_Clamp = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Clamp.BP_ValuableItem_Clamp_C",
		ValuableItem_Wrench_3 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Wrench_3.BP_ValuableItem_Wrench_3_C",
		ValuableItem_Wrench_4 = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Wrench_4.BP_ValuableItem_Wrench_4_C",

		Ashes = {
			Ash_small = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_small.BP_Ash_small_C",
			Ash_Medium = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Medium.BP_Ash_Medium_C",
			Ash_Big = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Big.BP_Ash_Big_C",
			Ash_Item1 = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Item1.BP_Ash_Item1_C",
			Ash_Item2 = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Item2.BP_Ash_Item2_C",
			Ash_Item3 = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Item3.BP_Ash_Item3_C",
		},

		Arts = {
			ValuableArt_Box = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_Box.BP_ValuableArt_Box_C",
			ValuableArt_Brush = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_Brush.BP_ValuableArt_Brush_C",
			ValuableArt_Clock = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_Clock.BP_ValuableArt_Clock_C",
			ValuableArt_Cup = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_Cup.BP_ValuableArt_Cup_C",
			ValuableArt_Soap = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_Soap.BP_ValuableArt_Soap_C",
			ValuableArt_Spoon = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_Spoon.BP_ValuableArt_Spoon_C",
			ValuableArt_Wrench = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_Wrench.BP_ValuableArt_Wrench_C",
		},

		ForInstruction = {
			ValuableItem_ForInstruction = "/Game/ITR2/BPs/Items/Valuables/ForInstruction/BP_ValuableItem_ForInstruction.BP_ValuableItem_ForInstruction_C",
		},

	},

	Player = {
		PlayerDeathPoint = "/Game/ITR2/BPs/Player/BP_PlayerDeathPoint.BP_PlayerDeathPoint_C",
	},

	QA = {
		QAEnemyCounter = "/Game/ITR2/BPs/QA/BP_QAEnemyCounter.BP_QAEnemyCounter_C",
		QARangefinder = "/Game/ITR2/BPs/QA/BP_QARangefinder.BP_QARangefinder_C",
	},

	MissionItems = {
		MissionCase = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionCase.BP_MissionCase_C",
		MissionItem_OutdatedSensor = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_OutdatedSensor.BP_MissionItem_OutdatedSensor_C",
		MissionItem_Amplifier = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_Amplifier.BP_MissionItem_Amplifier_C",
		MissionItem3 = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem3.BP_MissionItem3_C",
		MissionItem_TripodStandard = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_TripodStandard.BP_MissionItem_TripodStandard_C",
		MissionItem_TripodDistortion = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_TripodDistortion.BP_MissionItem_TripodDistortion_C",
		MissionItem_TED = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_TED.BP_MissionItem_TED_C",
		MissionItem_Bracelet = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_Bracelet.BP_MissionItem_Bracelet_C",
		MissionItem_Compass = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_Compass.BP_MissionItem_Compass_C",
		MissionItem_Battery = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_Battery.BP_MissionItem_Battery_C",
		MissionItem_ArtContainerPrototype = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_ArtContainerPrototype.BP_MissionItem_ArtContainerPrototype_C",
		MissionItem_RatCase = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_RatCase.BP_MissionItem_RatCase_C",
		MissionItem_Key = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_Key.BP_MissionItem_Key_C",
		MissionItem_ArtContainer = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_ArtContainer.BP_MissionItem_ArtContainer_C",
		MissionItem_PortalBracelet = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_PortalBracelet.BP_MissionItem_PortalBracelet_C",
		MissionItem_PortalProbe = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_PortalProbe.BP_MissionItem_PortalProbe_C",
		MissionItem_PortalProbe_Prototype = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_PortalProbe_Prototype.BP_MissionItem_PortalProbe_Prototype_C",
		MissionItem_BatteryRat = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_BatteryRat.BP_MissionItem_BatteryRat_C",
		MissionItem_TripodTopPriority = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_TripodTopPriority.BP_MissionItem_TripodTopPriority_C",

		Mission_07 = {
			HandDoorActivator = "/Game/ITR2/BPs/Items/MissionItems/Mission_07/BP_HandDoorActivator.BP_HandDoorActivator_C",
		},

	},

	Cleaning = {
		OilSpray = "/Game/ITR2/BPs/Items/Cleaning/BP_OilSpray.BP_OilSpray_C",
		CleaningBrush = "/Game/ITR2/BPs/Items/Cleaning/BP_CleaningBrush.BP_CleaningBrush_C",
		TestRod_2 = "/Game/ITR2/BPs/Items/Cleaning/BP_TestRod_2.BP_TestRod_2_C",
		Ramrod = "/Game/ITR2/BPs/Items/Cleaning/BP_Ramrod.BP_Ramrod_C",
		Cleaning_ToothBrush_CH = "/Game/ITR2/BPs/Items/Cleaning/BP_Cleaning_ToothBrush_CH.BP_Cleaning_ToothBrush_CH_C",
	},

	Walkie_talkie = {
		Walkie_talkie = "/Game/ITR2/BPs/Items/Walkie_talkie/BP_Walkie_talkie.BP_Walkie_talkie_C",
	},

	Grenades = {
		Grenade_RDG2 = "/Game/ITR2/BPs/Items/Grenades/BP_Grenade_RDG2.BP_Grenade_RDG2_C",
		RDG2_Pin = "/Game/ITR2/BPs/Items/Grenades/BP_RDG2_Pin.BP_RDG2_Pin_C",
		Grenade_F1 = "/Game/ITR2/BPs/Items/Grenades/BP_Grenade_F1.BP_Grenade_F1_C",
		F1_Pin = "/Game/ITR2/BPs/Items/Grenades/BP_F1_Pin.BP_F1_Pin_C",
		Grenade_M67 = "/Game/ITR2/BPs/Items/Grenades/BP_Grenade_M67.BP_Grenade_M67_C",
		M67_Pin = "/Game/ITR2/BPs/Items/Grenades/BP_M67_Pin.BP_M67_Pin_C",
		Grenade_RGD5 = "/Game/ITR2/BPs/Items/Grenades/BP_Grenade_RGD5.BP_Grenade_RGD5_C",
		RGD5_Pin = "/Game/ITR2/BPs/Items/Grenades/BP_RGD5_Pin.BP_RGD5_Pin_C",
		Grenade_RGN = "/Game/ITR2/BPs/Items/Grenades/BP_Grenade_RGN.BP_Grenade_RGN_C",
		RGN_RGO_Pin = "/Game/ITR2/BPs/Items/Grenades/BP_RGN_RGO_Pin.BP_RGN_RGO_Pin_C",
		Grenade_RGO = "/Game/ITR2/BPs/Items/Grenades/BP_Grenade_RGO.BP_Grenade_RGO_C",
	},

	Flare = {
		FlareLauncher = "/Game/ITR2/BPs/Items/Flare/BP_FlareLauncher.BP_FlareLauncher_C",
	},

	Outfits = {
		OutfitExplorerBasic = "/Game/ITR2/BPs/Items/Outfits/BP_OutfitExplorerBasic.BP_OutfitExplorerBasic_C",
	},

	Melee = {
		knife = "/Game/ITR2/BPs/Items/Melee/BP_knife.BP_knife_C",
	},

	Paint = {

		Colours = {
			PaintSpray_Clear = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Clear.BP_PaintSpray_Clear_C",
			PaintSpray_LightGray = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_LightGray.BP_PaintSpray_LightGray_C",
			PaintSpray_Brown = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Brown.BP_PaintSpray_Brown_C",
			PaintSpray_Olive = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Olive.BP_PaintSpray_Olive_C",
			PaintSpray_Tan = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Tan.BP_PaintSpray_Tan_C",
			PaintSpray_Black = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Black.BP_PaintSpray_Black_C",
			PaintSpray_Blue = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Blue.BP_PaintSpray_Blue_C",
			PaintSpray_DarkGrey = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_DarkGrey.BP_PaintSpray_DarkGrey_C",
			PaintSpray_Khaki = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Khaki.BP_PaintSpray_Khaki_C",
			PaintSpray_Navy = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Navy.BP_PaintSpray_Navy_C",
			PaintSpray_Orange = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Orange.BP_PaintSpray_Orange_C",
			PaintSpray_Red = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Red.BP_PaintSpray_Red_C",
			PaintSpray_Sand = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Sand.BP_PaintSpray_Sand_C",
			PaintSpray_White = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_White.BP_PaintSpray_White_C",
			PaintSpray_Yellow = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Yellow.BP_PaintSpray_Yellow_C",
			PaintSpray_Purple = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Purple.BP_PaintSpray_Purple_C",
			PaintSpray_CommiteBlue = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_CommiteBlue.BP_PaintSpray_CommiteBlue_C",
			PaintSpray_DarkRed = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_DarkRed.BP_PaintSpray_DarkRed_C",
			PaintSpray_DarkYellow = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_DarkYellow.BP_PaintSpray_DarkYellow_C",
			PaintSpray_DarkPurple = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_DarkPurple.BP_PaintSpray_DarkPurple_C",
			PaintSpray_DarkOrange = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_DarkOrange.BP_PaintSpray_DarkOrange_C",
			PaintSpray_Green = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_Green.BP_PaintSpray_Green_C",
			PaintSpray_DarkGreen = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_DarkGreen.BP_PaintSpray_DarkGreen_C",
			PaintSpray_CommitePink = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_CommitePink.BP_PaintSpray_CommitePink_C",
			PaintSpray_CommiteDarkPink = "/Game/ITR2/BPs/Items/Paint/Colours/BP_PaintSpray_CommiteDarkPink.BP_PaintSpray_CommiteDarkPink_C",
		},

		Patterns = {
			PaintPattern_Ch_Bark = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Bark.BP_PaintPattern_Ch_Bark_C",
			PaintPattern_Ch_Branches = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Branches.BP_PaintPattern_Ch_Branches_C",
			PaintPattern_Ch_Chimera = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Chimera.BP_PaintPattern_Ch_Chimera_C",
			PaintPattern_Ch_Classic = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Classic.BP_PaintPattern_Ch_Classic_C",
			PaintPattern_Ch_Desert = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Desert.BP_PaintPattern_Ch_Desert_C",
			PaintPattern_Ch_Forest = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Forest.BP_PaintPattern_Ch_Forest_C",
			PaintPattern_Ch_Geometry = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Geometry.BP_PaintPattern_Ch_Geometry_C",
			PaintPattern_Ch_Pixel = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Pixel.BP_PaintPattern_Ch_Pixel_C",
			PaintPattern_Ch_Swamp = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Swamp.BP_PaintPattern_Ch_Swamp_C",
			PaintPattern_Ch_Tiger = "/Game/ITR2/BPs/Items/Paint/Patterns/BP_PaintPattern_Ch_Tiger.BP_PaintPattern_Ch_Tiger_C",
		},

	},

	Anomalies = {

		Parasites = {
			Parasite = "/Game/ITR2/BPs/Anomalies/Parasites/BP_Parasite.BP_Parasite_C",
		},

	},

}

return Items