--AUTO GENERATED BY ITR2 ITEM UPDATE SCRIPT--
local Items = {
	Probes = {
		ProbeSack = "/Game/ITR2/BPs/Items/Probes/BP_ProbeSack.BP_ProbeSack_C",
		RadiusAmmo_Probe = "/Game/ITR2/BPs/Items/Probes/BP_RadiusAmmo_Probe.BP_RadiusAmmo_Probe_C",
	},

	Firearms = {
		Primary = {
			AK74 = {
				AK_74_Mag_Red = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Red.BP_AK_74_Mag_Red_C",
				AK_74_Mag_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Black.BP_AK_74_Mag_Black_C",
				AK_74_Mag_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Long.BP_AK_74_Mag_Long_C",
				AKSu74N_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AKSu74N_S.BP_AKSu74N_S_C",
				AKSu74N = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AKSu74N.BP_AKSu74N_C",
				AK74N_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74N_S.BP_AK74N_S_C",
				AK74N = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74N.BP_AK74N_C",
				AK74M = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74M.BP_AK74M_C",
				AK74_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74_Modular_Base.BP_AK74_Modular_Base_C",
				AK74_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74_Modular_S.BP_AK74_Modular_S_C",
				AKSu_Modular_base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AKSu_Modular_base.BP_AKSu_Modular_base_C",
				AKSu_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AKSu_Modular_S.BP_AKSu_Modular_S_C",

				AK74_Parts = {
					Ak74_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AK74_Parts/BP_Ak74_Barrel_Base.BP_Ak74_Barrel_Base_C",
					Ak74_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AK74_Parts/BP_Ak74_Barrel_Base_S.BP_Ak74_Barrel_Base_S_C",
				},

				AKSu_parts = {
					AKSu_Handguard_Wood1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Handguard_Wood1.BP_AKSu_Handguard_Wood1_C",
					AKSu_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Handguard_Railed.BP_AKSu_Handguard_Railed_C",
					AKSu_Handguard_Wood_Old = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Handguard_Wood_Old.BP_AKSu_Handguard_Wood_Old_C",
					AKSu_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Barrel_Base.BP_AKSu_Barrel_Base_C",
					AKSu_Barrel_Base_Rusty = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Barrel_Base_Rusty.BP_AKSu_Barrel_Base_Rusty_C",
					AKSu_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Lid_Basic.BP_AKSu_Lid_Basic_C",
					AKSu_Lid_Basic_Rusty = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Lid_Basic_Rusty.BP_AKSu_Lid_Basic_Rusty_C",
					AKSu_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/AKSu_parts/BP_AKSu_Lid_Railed.BP_AKSu_Lid_Railed_C",
				},

			},

			SKS = {
				SKS_Mag_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_Mag_Short.BP_SKS_Mag_Short_C",
				SKS_M = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_M.BP_SKS_M_C",
				SKS = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS.BP_SKS_C",
				SKS_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_S.BP_SKS_S_C",
			},

			AKM = {
				AKM_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Mag.BP_AKM_Mag_C",
				AKM_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_S.BP_AKM_S_C",
				AKM = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM.BP_AKM_C",
				AKM_M = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_M.BP_AKM_M_C",
				AKM_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Modular_Base.BP_AKM_Modular_Base_C",
				AKM_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Modular_S.BP_AKM_Modular_S_C",

				AKM_Parts = {
					AKM_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/AKM_Parts/BP_AKM_Barrel_Base.BP_AKM_Barrel_Base_C",
					AKM_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/AKM_Parts/BP_AKM_Barrel_Base_S.BP_AKM_Barrel_Base_S_C",
				},

			},

			Groza = {
				Groza_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza_Mag.BP_Groza_Mag_C",
				Groza_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza_S.BP_Groza_S_C",
				Groza = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza.BP_Groza_C",

				Groza_Parts = {
					Rail_Groza = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/Groza_Parts/BP_Rail_Groza.BP_Rail_Groza_C",
				},

			},

			Saiga = {
				Saiga_Mag_Short2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Mag_Short2.BP_Saiga_Mag_Short2_C",
				Saiga_Mag_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Mag_Long.BP_Saiga_Mag_Long_C",
				Saiga_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_S.BP_Saiga_S_C",
				Saiga = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga.BP_Saiga_C",
				Saiga_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Modular_Base.BP_Saiga_Modular_Base_C",
				Saiga_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Modular_S.BP_Saiga_Modular_S_C",

				Saiga_parts = {
					Saiga_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Barrel_Long.BP_Saiga_Barrel_Long_C",
					Saiga_Barrel_Long_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Barrel_Long_S.BP_Saiga_Barrel_Long_S_C",
					Saiga_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Barrel_Short.BP_Saiga_Barrel_Short_C",
					Saiga_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Handguard_Base.BP_Saiga_Handguard_Base_C",
					Saiga_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Handguard_Railed.BP_Saiga_Handguard_Railed_C",
					Saiga_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Lid_Basic.BP_Saiga_Lid_Basic_C",
					Saiga_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/Saiga_parts/BP_Saiga_Lid_Railed.BP_Saiga_Lid_Railed_C",
				},

			},

			Val_and_VSS = {
				VSS_Mag_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VSS_Mag_Short.BP_VSS_Mag_Short_C",
				AS_Val_Mag_Med = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_AS_Val_Mag_Med.BP_AS_Val_Mag_Med_C",
				VSS_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VSS_S.BP_VSS_S_C",
				VSS = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VSS.BP_VSS_C",
				AS_VAL_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_AS_VAL_S.BP_AS_VAL_S_C",
				AS_VAL = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_AS_VAL.BP_AS_VAL_C",
			},

			Kedr = {
				Kedr_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Kedr/BP_Kedr_Mag.BP_Kedr_Mag_C",
				Kedr_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Kedr/BP_Kedr_S.BP_Kedr_S_C",
				Kedr = "/Game/ITR2/BPs/Items/Firearms/Primary/Kedr/BP_Kedr.BP_Kedr_C",
			},

			Bizon = {
				Bizon_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_Mag.BP_Bizon_Mag_C",
				Bizon_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_S.BP_Bizon_S_C",
				Bizon = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon.BP_Bizon_C",
				Bizon_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_Modular_Base.BP_Bizon_Modular_Base_C",
				Bizon_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_Modular_S.BP_Bizon_Modular_S_C",

				Bizon_Parts = {
					Bizon_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Barrel_Base.BP_Bizon_Barrel_Base_C",
					Bizon_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Barrel_Base_S.BP_Bizon_Barrel_Base_S_C",
					Bizon_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Barrel_Long.BP_Bizon_Barrel_Long_C",
					Bizon_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Handguard_Base.BP_Bizon_Handguard_Base_C",
					Bizon_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Handguard_Railed.BP_Bizon_Handguard_Railed_C",
					Bizon_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Lid_Basic.BP_Bizon_Lid_Basic_C",
					Bizon_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/Bizon_Parts/BP_Bizon_Lid_Railed.BP_Bizon_Lid_Railed_C",
				},

			},

			M4A1 = {
				M4A1_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1_Mag.BP_M4A1_Mag_C",
				M4A1_S = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1_S.BP_M4A1_S_C",
				M4A1 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1.BP_M4A1_C",
				M4A1_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1_Modular_Base.BP_M4A1_Modular_Base_C",
				M4A1_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/BP_M4A1_Modular_S.BP_M4A1_Modular_S_C",

				M4A1_Parts = {
					Rail_M4A1_Classik = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_Rail_M4A1_Classik.BP_Rail_M4A1_Classik_C",
					M4A1_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Short.BP_M4A1_Barrel_Short_C",
					M4A1_Barrel_Short_S = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Short_S.BP_M4A1_Barrel_Short_S_C",
					M4A1_Barrel_Medium = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Medium.BP_M4A1_Barrel_Medium_C",
					M4A1_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Barrel_Long.BP_M4A1_Barrel_Long_C",
					M4A1_Handguard_Classik = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Classik.BP_M4A1_Handguard_Classik_C",
					M4A1_Handguard_Classik_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Classik_2.BP_M4A1_Handguard_Classik_2_C",
					M4A1_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Railed.BP_M4A1_Handguard_Railed_C",
					M4A1_Handguard_Railed_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_Railed_2.BP_M4A1_Handguard_Railed_2_C",
					M4A1_Handguard_RailedSP_M1 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedSP_M1.BP_M4A1_Handguard_RailedSP_M1_C",
					M4A1_Handguard_RailedSP_M2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedSP_M2.BP_M4A1_Handguard_RailedSP_M2_C",
					M4A1_Handguard_RailedSP_M3 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedSP_M3.BP_M4A1_Handguard_RailedSP_M3_C",
					M4A1_Handguard_RailedKTT_M1 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M1.BP_M4A1_Handguard_RailedKTT_M1_C",
					M4A1_Handguard_RailedKTT_M2 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M2.BP_M4A1_Handguard_RailedKTT_M2_C",
					M4A1_Handguard_RailedKTT_M3 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M3.BP_M4A1_Handguard_RailedKTT_M3_C",
					M4A1_Handguard_RailedKTT_M4 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M4.BP_M4A1_Handguard_RailedKTT_M4_C",
					M4A1_Handguard_RailedKTT_M5 = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_Handguard_RailedKTT_M5.BP_M4A1_Handguard_RailedKTT_M5_C",
					M4A1_GasBlock_Classik = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_GasBlock_Classik.BP_M4A1_GasBlock_Classik_C",
					M4A1_GasBlock_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_GasBlock_Railed.BP_M4A1_GasBlock_Railed_C",
					M4A1_GasBlock_Inner = "/Game/ITR2/BPs/Items/Firearms/Primary/M4A1/M4A1_Parts/BP_M4A1_GasBlock_Inner.BP_M4A1_GasBlock_Inner_C",
				},

			},

			SVD = {
				SVD_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_Mag.BP_SVD_Mag_C",
				SVD_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_S.BP_SVD_S_C",
				SVD_N = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_N.BP_SVD_N_C",
				SVD_M = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_M.BP_SVD_M_C",
				SVD_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_Modular_Base.BP_SVD_Modular_Base_C",
				SVD_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/BP_SVD_Modular_S.BP_SVD_Modular_S_C",

				SVDParts = {
					SVD_Barrel_AdapterOnBarrell = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_AdapterOnBarrell.BP_SVD_Barrel_AdapterOnBarrell_C",
					SVD_Barrel_Muzzle_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_Muzzle_1.BP_SVD_Barrel_Muzzle_1_C",
					SVD_Stock_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Stock_Handle.BP_SVD_Stock_Handle_C",
					SVD_Stock_Handle_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Stock_Handle_S.BP_SVD_Stock_Handle_S_C",
					SVD_StockAdapter_AR_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_StockAdapter_AR_1.BP_SVD_StockAdapter_AR_1_C",
					SVD_Lid_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Lid_Base.BP_SVD_Lid_Base_C",
					SVD_Handguard_Railed_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Handguard_Railed_1.BP_SVD_Handguard_Railed_1_C",
					SVD_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Handguard_Base.BP_SVD_Handguard_Base_C",
					SVD_Handguard_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Handguard_S.BP_SVD_Handguard_S_C",
					SVD_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_Base.BP_SVD_Barrel_Base_C",
					SVD_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SVD/SVDParts/BP_SVD_Barrel_Base_S.BP_SVD_Barrel_Base_S_C",
				},

			},

			G36 = {
				G36_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_Mag.BP_G36_Mag_C",
				G36_S = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_S.BP_G36_S_C",
				G36_M_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_M_Short.BP_G36_M_Short_C",
				G36_M_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_M_Long.BP_G36_M_Long_C",
				G36_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_Modular_Base.BP_G36_Modular_Base_C",
				G36_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/BP_G36_Modular_S.BP_G36_Modular_S_C",

				G36_Parts = {
					Rail_Plank_G36 = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_Plank_G36.BP_Rail_Plank_G36_C",
					Rail_Plank_G36_v2 = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_Plank_G36_v2.BP_Rail_Plank_G36_v2_C",
					Rail_G36 = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_G36.BP_Rail_G36_C",
					Rail_G36_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_G36_Short.BP_Rail_G36_Short_C",
					Rail_G36_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_Rail_G36_Long.BP_Rail_G36_Long_C",
					G36_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Short.BP_G36_Barrel_Short_C",
					G36_Barrel_Short_S = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Short_S.BP_G36_Barrel_Short_S_C",
					G36_Barrel_Medium = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Medium.BP_G36_Barrel_Medium_C",
					G36_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Barrel_Long.BP_G36_Barrel_Long_C",
					G36_Handguard_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Short.BP_G36_Handguard_Short_C",
					G36_Handguard_Medium = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Medium.BP_G36_Handguard_Medium_C",
					G36_Handguard_Medium_S = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Medium_S.BP_G36_Handguard_Medium_S_C",
					G36_Handguard_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Handguard_Long.BP_G36_Handguard_Long_C",
					G36_Stock_Folding = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Stock_Folding.BP_G36_Stock_Folding_C",
					G36_Stock_Teleskopic = "/Game/ITR2/BPs/Items/Firearms/Primary/G36/G36_Parts/BP_G36_Stock_Teleskopic.BP_G36_Stock_Teleskopic_C",
				},

			},

			BenelliM2 = {
				BenelliM2_6_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_6_Mag.BP_BenelliM2_6_Mag_C",
				BenelliM2_8_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_8_Mag.BP_BenelliM2_8_Mag_C",
				BenelliM2_2_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_2_Mag.BP_BenelliM2_2_Mag_C",
				BenelliM2 = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2.BP_BenelliM2_C",
				BenelliM2_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_Modular_Base.BP_BenelliM2_Modular_Base_C",
				BenelliM2_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/BP_BenelliM2_Modular_S.BP_BenelliM2_Modular_S_C",

				Benelli_Parts = {
					Rail_BenelliM2 = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Rail_BenelliM2.BP_Rail_BenelliM2_C",
					Rail_BenelliM2_Underbarrel = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Rail_BenelliM2_Underbarrel.BP_Rail_BenelliM2_Underbarrel_C",
					Benelli_Stock_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Stock_Handle.BP_Benelli_Stock_Handle_C",
					Benelli_Stock_Handle_Ergo = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Stock_Handle_Ergo.BP_Benelli_Stock_Handle_Ergo_C",
					Benelli_Handle_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handle_1.BP_Benelli_Handle_1_C",
					Benelli_Handle_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handle_2.BP_Benelli_Handle_2_C",
					Benelli_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Base.BP_Benelli_Barrel_Base_C",
					Benelli_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Base_S.BP_Benelli_Barrel_Base_S_C",
					Benelli_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Short.BP_Benelli_Barrel_Short_C",
					Benelli_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Barrel_Long.BP_Benelli_Barrel_Long_C",
					Benelli_Handguard_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handguard_Base.BP_Benelli_Handguard_Base_C",
					Benelli_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handguard_Railed.BP_Benelli_Handguard_Railed_C",
					Benelli_Handguard_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/BenelliM2/Benelli_Parts/BP_Benelli_Handguard_Short.BP_Benelli_Handguard_Short_C",
				},

			},

			SR25 = {
				SR25_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/BP_SR25_Mag.BP_SR25_Mag_C",
				SR25_M = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/BP_SR25_M.BP_SR25_M_C",
				SR25_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/BP_SR25_Modular_Base.BP_SR25_Modular_Base_C",
				SR25_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/BP_SR25_Modular_S.BP_SR25_Modular_S_C",

				SR25_Parts = {
					SR25_Barrel_Small = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Small.BP_SR25_Barrel_Small_C",
					SR25_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Base.BP_SR25_Barrel_Base_C",
					SR25_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Base_S.BP_SR25_Barrel_Base_S_C",
					SR25_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Barrel_Long.BP_SR25_Barrel_Long_C",
					SR25_Handguard_Railed_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/SR25/SR25_Parts/BP_SR25_Handguard_Railed_1.BP_SR25_Handguard_Railed_1_C",
				},

			},

			MP9 = {
				MP9_Mag30 = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/BP_MP9_Mag30.BP_MP9_Mag30_C",
				MP9_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/BP_MP9_Black.BP_MP9_Black_C",
				MP9_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/BP_MP9_Modular_Base.BP_MP9_Modular_Base_C",
				MP9_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/BP_MP9_Modular_S.BP_MP9_Modular_S_C",

				MP9_parts = {
					Rail_MP9_DownRail = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_Rail_MP9_DownRail.BP_Rail_MP9_DownRail_C",
					Rail_MP9_LeftRail = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_Rail_MP9_LeftRail.BP_Rail_MP9_LeftRail_C",
					Rail_MP9_RightRail = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_Rail_MP9_RightRail.BP_Rail_MP9_RightRail_C",
					MP9_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_MP9_Handguard_Railed.BP_MP9_Handguard_Railed_C",
					MP9_Stock_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/MP9/MP9_parts/BP_MP9_Stock_Base.BP_MP9_Stock_Base_C",
				},

			},

			Vityaz = {
				Vityaz_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/BP_Vityaz_Mag.BP_Vityaz_Mag_C",
				Vityaz_M = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/BP_Vityaz_M.BP_Vityaz_M_C",
				Vityaz_Modular = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/BP_Vityaz_Modular.BP_Vityaz_Modular_C",
				Vityaz_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/BP_Vityaz_Modular_S.BP_Vityaz_Modular_S_C",

				Vityaz_parts = {
					Ak74_Vityaz_Plastic_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Ak74_Vityaz_Plastic_Black.BP_Ak74_Vityaz_Plastic_Black_C",
					Vityaz_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Barrel_Base.BP_Vityaz_Barrel_Base_C",
					Vityaz_Barrel_Base_S = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Barrel_Base_S.BP_Vityaz_Barrel_Base_S_C",
					Vityaz_Barrel_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Barrel_Long.BP_Vityaz_Barrel_Long_C",
					Vityaz_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Lid_Basic.BP_Vityaz_Lid_Basic_C",
					Vityaz_Lid_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/Vityaz/Vityaz_parts/BP_Vityaz_Lid_Railed.BP_Vityaz_Lid_Railed_C",
				},

			},

			KEDR_PP_91 = {
				KEDR_PP_91_Mag_20 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Mag_20.BP_KEDR_PP-91_Mag_20_C",
				KEDR_PP_91_Mag_30 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Mag_30.BP_KEDR_PP-91_Mag_30_C",
				KEDR_PP_91_Mag_40 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Mag_40.BP_KEDR_PP-91_Mag_40_C",
				KEDR_PP_91 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91.BP_KEDR_PP-91_C",
				KEDR_PP_91_Modular_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Modular_Base.BP_KEDR_PP-91_Modular_Base_C",
				KEDR_PP_91_Modular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/BP_KEDR_PP-91_Modular_S.BP_KEDR_PP-91_Modular_S_C",

				Kedr_Parts = {
					Rail_Kedr_HandGuard_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Rail_Kedr_HandGuard_Long.BP_Rail_Kedr_HandGuard_Long_C",
					Rail_Kedr_HandGuard_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Rail_Kedr_HandGuard_Short.BP_Rail_Kedr_HandGuard_Short_C",
					Kedr_Stock_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Stock_Base.BP_Kedr_Stock_Base_C",
					Kedr_StockAdapter_AK = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_StockAdapter_AK.BP_Kedr_StockAdapter_AK_C",
					Kedr_StockAdapter_AR = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_StockAdapter_AR.BP_Kedr_StockAdapter_AR_C",
					Kedr_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Lid_Basic.BP_Kedr_Lid_Basic_C",
					Kedr_Handguard_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Handguard_Railed.BP_Kedr_Handguard_Railed_C",
					Kedr_Handguard_Railed_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/KEDR_PP-91/Kedr_Parts/BP_Kedr_Handguard_Railed_2.BP_Kedr_Handguard_Railed_2_C",
				},

			},

			Mosin = {
				Mosin_Mag_Internal = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_Mag_Internal.BP_Mosin_Mag_Internal_C",
				Mosin_Clip = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_Clip.BP_Mosin_Clip_C",
				Mosin_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_Mag.BP_Mosin_Mag_C",
				Mosin = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin.BP_Mosin_C",
				Mosin_modular = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_modular.BP_Mosin_modular_C",
				Mosin_modular_S_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/BP_Mosin_modular_S_2.BP_Mosin_modular_S_2_C",

				Mosin_parts = {
					Mosin_ForeSight = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_ForeSight.BP_Mosin_ForeSight_C",
					Mosin_ForeSight_Rail = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_ForeSight_Rail.BP_Mosin_ForeSight_Rail_C",
					Mosin_KochetovaBase = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_KochetovaBase.BP_Mosin_KochetovaBase_C",
					Scope_PU_Rail = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Scope_PU_Rail.BP_Scope_PU_Rail_C",
					Side_Mosin_Bandolier = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Side_Mosin_Bandolier.BP_Side_Mosin_Bandolier_C",
					Mosin_Bandolier_Stock_L2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Bandolier_Stock_L2.BP_Mosin_Bandolier_Stock_L2_C",
					Mosin_Bandolier_Stock_R2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Bandolier_Stock_R2.BP_Mosin_Bandolier_Stock_R2_C",
					Mosin_LongStock_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Wood.BP_Mosin_LongStock_Wood_C",
					Mosin_LongStock_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Plastic.BP_Mosin_LongStock_Plastic_C",
					Mosin_LongStock_Plastic_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Plastic_2.BP_Mosin_LongStock_Plastic_2_C",
					Mosin_LongStock_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Short.BP_Mosin_LongStock_Short_C",
					Mosin_LongStock_Short_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_LongStock_Short_2.BP_Mosin_LongStock_Short_2_C",
					Mosin_Barrel_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Barrel_Base.BP_Mosin_Barrel_Base_C",
					Mosin_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Barrel_Short.BP_Mosin_Barrel_Short_C",
					Mosin_Barrel_Short_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Mosin/Mosin_parts/BP_Mosin_Barrel_Short_2.BP_Mosin_Barrel_Short_2_C",
				},

			},

			IZh_27 = {
				Iz27_SawOff_S = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_SawOff_S.BP_Iz27_SawOff_S_C",
				Iz27_SawOff = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_SawOff.BP_Iz27_SawOff_C",
				Iz27_S = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_S.BP_Iz27_S_C",
				Iz27 = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27.BP_Iz27_C",
				Iz27_M = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_M.BP_Iz27_M_C",
				Iz27_FullModular = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_FullModular.BP_Iz27_FullModular_C",
				Iz27_FullModular_S = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_FullModular_S.BP_Iz27_FullModular_S_C",

				Iz27_Parts = {
					Rail_ShotgunDB_Middle = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Rail_ShotgunDB_Middle.BP_Rail_ShotgunDB_Middle_C",
					Rail_ShotgunDB_Underbarrel = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Rail_ShotgunDB_Underbarrel.BP_Rail_ShotgunDB_Underbarrel_C",
					Iz27_Handguard_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Handguard_Wood.BP_Iz27_Handguard_Wood_C",
					Iz27_Handguard_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Handguard_Plastic.BP_Iz27_Handguard_Plastic_C",
					Iz27_Stock_Handle_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Stock_Handle_Wood.BP_Iz27_Stock_Handle_Wood_C",
					Iz27_Handle_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Handle_Wood.BP_Iz27_Handle_Wood_C",
					Iz27_Stock_Handle_Plastic = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Iz27_Stock_Handle_Plastic.BP_Iz27_Stock_Handle_Plastic_C",
					Izh27_Barrel_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Izh27_Barrel_Short.BP_Izh27_Barrel_Short_C",
					Izh27_Barrel_Short_S = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Izh27_Barrel_Short_S.BP_Izh27_Barrel_Short_S_C",
					Izh27_Barrel_Long2 = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/Iz27_Parts/BP_Izh27_Barrel_Long2.BP_Izh27_Barrel_Long2_C",
				},

			},

			AK_Parts = {
				AK_Ak74_Handle_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Ak74_Handle_Basic.BP_AK_Ak74_Handle_Basic_C",
				AK_Ak74_Handle_Ergo1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Ak74_Handle_Ergo1.BP_AK_Ak74_Handle_Ergo1_C",
				AK_Ak74_Handle_Ergo2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Ak74_Handle_Ergo2.BP_AK_Ak74_Handle_Ergo2_C",
				Ak_AKM_Handle_Basic_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_Ak_AKM_Handle_Basic_1.BP_Ak_AKM_Handle_Basic_1_C",
				Ak_AKM_Handle_Basic_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_Ak_AKM_Handle_Basic_2.BP_Ak_AKM_Handle_Basic_2_C",
				AK_Saiga_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Saiga_Handle.BP_AK_Saiga_Handle_C",
				AK_Bizon_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Bizon_Handle.BP_AK_Bizon_Handle_C",
				AK_Vityaz_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Vityaz_Handle.BP_AK_Vityaz_Handle_C",
				AK_Kedr_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/BP_AK_Kedr_Handle.BP_AK_Kedr_Handle_C",

				AK74_AKM_Parts = {
					Ak74_Handguard_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Handguard_Wood.BP_Ak74_Handguard_Wood_C",
					Ak74_Plastic_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Plastic_Black.BP_Ak74_Plastic_Black_C",
					Ak74_Handguard_Rail1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Handguard_Rail1.BP_Ak74_Handguard_Rail1_C",
					AK74_Akm_Handguard_Wood1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Akm_Handguard_Wood1.BP_AK74_Akm_Handguard_Wood1_C",
					AK74_Akm_Handguard_Wood2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Akm_Handguard_Wood2.BP_AK74_Akm_Handguard_Wood2_C",
					Ak74_Handguard_Dong = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Handguard_Dong.BP_Ak74_Handguard_Dong_C",
					Ak74_Stock_FoldingFrame = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_FoldingFrame.BP_Ak74_Stock_FoldingFrame_C",
					Ak74_Stock_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_Wood.BP_Ak74_Stock_Wood_C",
					AK74_AKM_Stock_Wood_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_AKM_Stock_Wood_1.BP_AK74_AKM_Stock_Wood_1_C",
					Ak74_Stock_Plug = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_Plug.BP_Ak74_Stock_Plug_C",
					Ak74_Stock_Plastic_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Stock_Plastic_1.BP_Ak74_Stock_Plastic_1_C",
					Ak74_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Lid_Basic.BP_Ak74_Lid_Basic_C",
					Ak74_Lid_Rail1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_Ak74_Lid_Rail1.BP_Ak74_Lid_Rail1_C",
					AkM_Lid_Basic = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AkM_Lid_Basic.BP_AkM_Lid_Basic_C",
					AK74_Vityaz_Handguard_PL2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_PL2.BP_AK74_Vityaz_Handguard_PL2_C",
					AK74_Vityaz_Handguard_PL3 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_PL3.BP_AK74_Vityaz_Handguard_PL3_C",
					AK74_Vityaz_Handguard_Long_Railed = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_Long_Railed.BP_AK74_Vityaz_Handguard_Long_Railed_C",
					AK74_Vityaz_Handguard_Long_Railed_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK74_Vityaz_Handguard_Long_Railed_2.BP_AK74_Vityaz_Handguard_Long_Railed_2_C",
					AK_StockAdapter_AKBS = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK_StockAdapter_AKBS.BP_AK_StockAdapter_AKBS_C",
					AK_StockAdapter_AR = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AK74_AKM_Parts/BP_AK_StockAdapter_AR.BP_AK_StockAdapter_AR_C",
				},

				AKSu_Bizon_Saiga_parts = {
					AkBS_Stock_Bizon_Folding = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Stock_Bizon_Folding.BP_AkBS_Stock_Bizon_Folding_C",
					AkBS_Stock_Saiga = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Stock_Saiga.BP_AkBS_Stock_Saiga_C",
					AkBS_Vityaz_Stock_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Vityaz_Stock_1.BP_AkBS_Vityaz_Stock_1_C",
					AkBS_Vityaz_Stock_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Vityaz_Stock_2.BP_AkBS_Vityaz_Stock_2_C",
					AkBS_Vityaz_Stock_3 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Vityaz_Stock_3.BP_AkBS_Vityaz_Stock_3_C",
					AkBS_Stock_Saiga_Wood = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AkBS_Stock_Saiga_Wood.BP_AkBS_Stock_Saiga_Wood_C",
					AKBS_StockAdapter_AR_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AK_Parts/AKSu_Bizon_Saiga_parts/BP_AKBS_StockAdapter_AR_2.BP_AKBS_StockAdapter_AR_2_C",
				},

			},

			AR_Parts = {
				AR_SVD_Handle = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SVD_Handle.BP_AR_SVD_Handle_C",
				AR_SR25_Handle_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SR25_Handle_Base.BP_AR_SR25_Handle_Base_C",
				AR_M4A1_Handle_Base = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_M4A1_Handle_Base.BP_AR_M4A1_Handle_Base_C",
				AR_Handle_Ergo_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_Handle_Ergo_1.BP_AR_Handle_Ergo_1_C",
				AR_Handle_Ergo_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_Handle_Ergo_2.BP_AR_Handle_Ergo_2_C",
				AR_SVD_Stock = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SVD_Stock.BP_AR_SVD_Stock_C",
				AR_M4A1_Stock_1 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_M4A1_Stock_1.BP_AR_M4A1_Stock_1_C",
				AR_M4A1_Stock_2 = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_M4A1_Stock_2.BP_AR_M4A1_Stock_2_C",
				AR_SR_25_Stock = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_SR-25_Stock.BP_AR_SR-25_Stock_C",
				AR_Light = "/Game/ITR2/BPs/Items/Firearms/Primary/AR_Parts/BP_AR_Light.BP_AR_Light_C",
			},

		},

		Secondary = {
			PM = {
				Mag_PM = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_Mag_PM.BP_Mag_PM_C",
				Mag_PM_Long = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_Mag_PM_Long.BP_Mag_PM_Long_C",
				PM = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM.BP_PM_C",
				PM_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM_S.BP_PM_S_C",
				PM_mod = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM_mod.BP_PM_mod_C",
			},

			Gsh18 = {
				Mag_Gsh18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Mag_Gsh18.BP_Mag_Gsh18_C",
				Gsh18_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Gsh18_S.BP_Gsh18_S_C",
				Gsh18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Gsh18.BP_Gsh18_C",
			},

			Beretta = {
				Mag_Beretta = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Mag_Beretta.BP_Mag_Beretta_C",
				Beretta_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Beretta_S.BP_Beretta_S_C",
				Beretta = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Beretta.BP_Beretta_C",
			},

			Glock_18 = {
				Mag_Glock_18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Mag_Glock_18.BP_Mag_Glock_18_C",
				Mag_Glock_18_Long = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Mag_Glock_18_Long.BP_Mag_Glock_18_Long_C",
				Glock_18_s = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Glock_18_s.BP_Glock_18_s_C",
				Glock_18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Glock_18.BP_Glock_18_C",
			},

			FORT17 = {
				Mag_FORT17 = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_Mag_FORT17.BP_Mag_FORT17_C",
				FORT17_S = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_FORT17_S.BP_FORT17_S_C",
				FORT17_N = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_FORT17_N.BP_FORT17_N_C",
				FORT17_M = "/Game/ITR2/BPs/Items/Firearms/Secondary/FORT17/BP_FORT17_M.BP_FORT17_M_C",
			},

		},

		Attachments = {
			Scopes = {
				Scope_PSO = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_PSO.BP_Scope_PSO_C",
				RDS_Cobra = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_Cobra.BP_RDS_Cobra_C",
				RDS_PK6 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_PK6.BP_RDS_PK6_C",
				Scope_HG = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_HG.BP_Scope_HG_C",
				Scope_NF = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_NF.BP_Scope_NF_C",
				RDS_Red_Dot = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_Red_Dot.BP_RDS_Red_Dot_C",
				RDS_EODECK = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_EODECK.BP_RDS_EODECK_C",
				RDS_OKB71 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_OKB71.BP_RDS_OKB71_C",
				RDS_T4 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_T4.BP_RDS_T4_C",
				Scope_PU = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_PU.BP_Scope_PU_C",
				M4A1_Foresight = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_M4A1_Foresight.BP_M4A1_Foresight_C",
				M4A1_Celik = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_M4A1_Celik.BP_M4A1_Celik_C",
				Scope_Magnifier = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_Magnifier.BP_Scope_Magnifier_C",
				Scope_G36_Plank_with_Optic = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_G36_Plank_with_Optic.BP_Scope_G36_Plank_with_Optic_C",
				RDS_G36_Special = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_G36_Special.BP_RDS_G36_Special_C",
				RDS_Dorris = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_Dorris.BP_RDS_Dorris_C",
				Scope_Magnifier_L = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_Magnifier_L.BP_Scope_Magnifier_L_C",
				Benelli_Foresight_A1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Benelli_Foresight_A1.BP_Benelli_Foresight_A1_C",
				Benelli_Foresight_A2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Benelli_Foresight_A2.BP_Benelli_Foresight_A2_C",
				BenelliM2_RearSight = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_BenelliM2_RearSight.BP_BenelliM2_RearSight_C",
			},

			Rails = {
				Rail_45deg = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_45deg.BP_Rail_45deg_C",
				Rail_45deg_R = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_45deg_R.BP_Rail_45deg_R_C",
				Rail_PistolOverUnder = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_PistolOverUnder.BP_Rail_PistolOverUnder_C",
				Rail_Riser_A = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Riser_A.BP_Rail_Riser_A_C",
				DovetailToRail = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_DovetailToRail.BP_DovetailToRail_C",
				DovetailToRail_Low = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_DovetailToRail_Low.BP_DovetailToRail_Low_C",
				Rail_Plate_Medium_1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Medium_1.BP_Rail_Plate_Medium_1_C",
				Rail_Plate_Medium_2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Medium_2.BP_Rail_Plate_Medium_2_C",
				Rail_Plate_Short_1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Short_1.BP_Rail_Plate_Short_1_C",
				Rail_Plate_Short_2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_Plate_Short_2.BP_Rail_Plate_Short_2_C",
				DovetailToRail_Vityaz = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_DovetailToRail_Vityaz.BP_DovetailToRail_Vityaz_C",
			},

			Illumination = {
				Att_Flashlight_small = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Flashlight_small.BP_Att_Flashlight_small_C",
				Att_Pointer_small = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Pointer_small.BP_Att_Pointer_small_C",
				Att_Flashlight_Big = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Flashlight_Big.BP_Att_Flashlight_Big_C",
			},

			Muzzles = {
				AK = {
					MuzzleAK_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_Base.BP_MuzzleAK_Base_C",
					MuzzleAK_DTK2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_DTK2.BP_MuzzleAK_DTK2_C",
					MuzzleAK_DTK1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_DTK1.BP_MuzzleAK_DTK1_C",
					MuzzleAK_M11 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_M11.BP_MuzzleAK_M11_C",
					MuzzleAKSu_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAKSu_Base.BP_MuzzleAKSu_Base_C",
					MuzzleAKM_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAKM_Base.BP_MuzzleAKM_Base_C",
					MuzzleBizon_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleBizon_Base.BP_MuzzleBizon_Base_C",
				},

				M4A1 = {
					MuzzleM4A1_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/M4A1/BP_MuzzleM4A1_Base.BP_MuzzleM4A1_Base_C",
					MuzzleG36_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/M4A1/BP_MuzzleG36_Base.BP_MuzzleG36_Base_C",
				},

				Saiga = {
					Muzzle_Saiga = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/Saiga/BP_Muzzle_Saiga.BP_Muzzle_Saiga_C",
				},

				Vityaz = {
					MuzzleVityaz_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/Vityaz/BP_MuzzleVityaz_Base.BP_MuzzleVityaz_Base_C",
				},

				SR25 = {
					Muzzle_SR25_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/SR25/BP_Muzzle_SR25_Base.BP_Muzzle_SR25_Base_C",
				},
			},

			Silencers = {
				Silencer_Pistol = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_Pistol.BP_Silencer_Pistol_C",
				Silencer_5_45 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_5_45.BP_Silencer_5_45_C",
				Silencer_5_56 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_5_56.BP_Silencer_5_56_C",
				Silencer_7_62_54 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_7_62_54.BP_Silencer_7_62_54_C",
				Silencer_7_62_51 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_7_62_51.BP_Silencer_7_62_51_C",
				Silencer_MP9 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_MP9.BP_Silencer_MP9_C",
			},

			AdditionalSlots = {
				Rail_ShotgunDB_Bandolier_4 = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_4.BP_Rail_ShotgunDB_Bandolier_4_C",
				Rail_ShotgunDB_Bandolier_8 = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_8.BP_Rail_ShotgunDB_Bandolier_8_C",
				Rail_ShotgunDB_Bandolier_Stock = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_Stock.BP_Rail_ShotgunDB_Bandolier_Stock_C",
				Rail_ShotgunDB_Bandolier_Stock_L = "/Game/ITR2/BPs/Items/Firearms/Attachments/AdditionalSlots/BP_Rail_ShotgunDB_Bandolier_Stock_L.BP_Rail_ShotgunDB_Bandolier_Stock_L_C",
			},

			Grips = {
				Erco = {
					VertGrip_Erco_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Erco/BP_VertGrip_Erco_Black.BP_VertGrip_Erco_Black_C",
					VertGrip_Erco_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Erco/BP_VertGrip_Erco_Green_CH.BP_VertGrip_Erco_Green_CH_C",
					VertGrip_Erco_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Erco/BP_VertGrip_Erco_Orange_CH.BP_VertGrip_Erco_Orange_CH_C",
				},

				TungusUp = {
					VertGrip_TungusUp_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/TungusUp/BP_VertGrip_TungusUp_Black.BP_VertGrip_TungusUp_Black_C",
					VertGrip_TungusUp_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/TungusUp/BP_VertGrip_TungusUp_Green_CH.BP_VertGrip_TungusUp_Green_CH_C",
					VertGrip_TungusUp_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/TungusUp/BP_VertGrip_TungusUp_Orange_CH.BP_VertGrip_TungusUp_Orange_CH_C",
				},

				Mokpick = {
					VertGrip_MockPick_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Mokpick/BP_VertGrip_MockPick_Black.BP_VertGrip_MockPick_Black_C",
					VertGrip_MockPick_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Mokpick/BP_VertGrip_MockPick_Green_CH.BP_VertGrip_MockPick_Green_CH_C",
					VertGrip_MockPick_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Mokpick/BP_VertGrip_MockPick_Orange_CH.BP_VertGrip_MockPick_Orange_CH_C",
				},

				Gobar = {
					VertGrip_Gobar_Black = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Gobar/BP_VertGrip_Gobar_Black.BP_VertGrip_Gobar_Black_C",
					VertGrip_Gobar_Green_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Gobar/BP_VertGrip_Gobar_Green_CH.BP_VertGrip_Gobar_Green_CH_C",
					VertGrip_Gobar_Orange_CH = "/Game/ITR2/BPs/Items/Firearms/Attachments/Grips/Gobar/BP_VertGrip_Gobar_Orange_CH.BP_VertGrip_Gobar_Orange_CH_C",
				},
			},
		},

	},

	Ammo = {
		AmmoBox = {
			AmmoBox_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_FMJ.BP_AmmoBox_9x18_FMJ_C",
			AmmoBox_9x18_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_Tracer.BP_AmmoBox_9x18_Tracer_C",
			AmmoBox_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x19_FMJ.BP_AmmoBox_9x19_FMJ_C",
			AmmoBox_9x19_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x19_Tracer.BP_AmmoBox_9x19_Tracer_C",
			AmmoBox_12x70_BuckShot = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_BuckShot.BP_AmmoBox_12x70_BuckShot_C",
			AmmoBox_12x70_Slug = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_Slug.BP_AmmoBox_12x70_Slug_C",
			AmmoBox_12x70_SlugTracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_SlugTracer.BP_AmmoBox_12x70_SlugTracer_C",
			AmmoBox_545x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_FMJ.BP_AmmoBox_545x39_FMJ_C",
			AmmoBox_545x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_Tracer.BP_AmmoBox_545x39_Tracer_C",
			AmmoBox_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_5-56x45_FMJ.BP_AmmoBox_5-56x45_FMJ_C",
			AmmoBox_5_56x45_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_5-56x45_Tracer.BP_AmmoBox_5-56x45_Tracer_C",
			AmmoBox_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x39_FMJ.BP_AmmoBox_7-62x39_FMJ_C",
			AmmoBox_7_62x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x39_Tracer.BP_AmmoBox_7-62x39_Tracer_C",
			AmmoBox_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x51_FMJ.BP_AmmoBox_7-62x51_FMJ_C",
			AmmoBox_7_62x51_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x51_Tracer.BP_AmmoBox_7-62x51_Tracer_C",
			AmmoBox_7_62x54R_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x54R_FMJ.BP_AmmoBox_7-62x54R_FMJ_C",
			AmmoBox_7_62x54R_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x54R_Tracer.BP_AmmoBox_7-62x54R_Tracer_C",
			AmmoBox_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x39_FMJ.BP_AmmoBox_9x39_FMJ_C",
			AmmoBox_9x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x39_Tracer.BP_AmmoBox_9x39_Tracer_C",
			AmmoBox_545x39_BP = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_BP.BP_AmmoBox_545x39_BP_C",
		},

		LargeAmmoBox = {
			AmmoBoxLarge_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x18_FMJ.BP_AmmoBoxLarge_9x18_FMJ_C",
			AmmoBoxLarge_9x18_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x18_TR.BP_AmmoBoxLarge_9x18_TR_C",
			AmmoBoxLarge_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x19_FMJ.BP_AmmoBoxLarge_9x19_FMJ_C",
			AmmoBoxLarge_9x19_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x19_TR.BP_AmmoBoxLarge_9x19_TR_C",
			AmmoBoxLarge_12x70_BuckShot = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_BuckShot.BP_AmmoBoxLarge_12x70_BuckShot_C",
			AmmoBoxLarge_12x70_Slug = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_Slug.BP_AmmoBoxLarge_12x70_Slug_C",
			AmmoBoxLarge_12x70_SlugTR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_SlugTR.BP_AmmoBoxLarge_12x70_SlugTR_C",
			AmmoBoxLarge_5_45x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_45x39_FMJ.BP_AmmoBoxLarge_5_45x39_FMJ_C",
			AmmoBoxLarge_5_45x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_45x39_TR.BP_AmmoBoxLarge_5_45x39_TR_C",
			AmmoBoxLarge_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_56x45_FMJ.BP_AmmoBoxLarge_5_56x45_FMJ_C",
			AmmoBoxLarge_5_56x45_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_56x45_TR.BP_AmmoBoxLarge_5_56x45_TR_C",
			AmmoBoxLarge_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x39_FMJ.BP_AmmoBoxLarge_7_62x39_FMJ_C",
			AmmoBoxLarge_7_62x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x39_TR.BP_AmmoBoxLarge_7_62x39_TR_C",
			AmmoBoxLarge_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x51_FMJ.BP_AmmoBoxLarge_7_62x51_FMJ_C",
			AmmoBoxLarge_7_62x51_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x51_TR.BP_AmmoBoxLarge_7_62x51_TR_C",
			AmmoBoxLarge_7_62x54_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x54_FMJ.BP_AmmoBoxLarge_7_62x54_FMJ_C",
			AmmoBoxLarge_7_62x54_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x54_TR.BP_AmmoBoxLarge_7_62x54_TR_C",
			AmmoBoxLarge_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x39_FMJ.BP_AmmoBoxLarge_9x39_FMJ_C",
			AmmoBoxLarge_9x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x39_TR.BP_AmmoBoxLarge_9x39_TR_C",
		},

		Cartridges = {
			_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_FMJ.BP_9x18_FMJ_C",
			_9x18_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_TR.BP_9x18_TR_C",
			_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x19_FMJ.BP_9x19_FMJ_C",
			_9x19_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x19_TR.BP_9x19_TR_C",
			_12g_Buckshot = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_Buckshot.BP_12g_Buckshot_C",
			_12g_Slug = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_Slug.BP_12g_Slug_C",
			_12g_SlugTracer = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_SlugTracer.BP_12g_SlugTracer_C",
			_5_45x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_FMJ.BP_5-45x39_FMJ_C",
			_5_45x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_TR.BP_5-45x39_TR_C",
			_5_45x39_BP = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_BP.BP_5-45x39_BP_C",
			_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-56x45_FMJ.BP_5-56x45_FMJ_C",
			_5_56x45_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-56x45_TR.BP_5-56x45_TR_C",
			_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x39_FMJ.BP_7-62x39_FMJ_C",
			_7_62x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x39_TR.BP_7-62x39_TR_C",
			_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x51_FMJ.BP_7-62x51_FMJ_C",
			_7_62x51_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x51_TR.BP_7-62x51_TR_C",
			_7_62x54R_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x54R_FMJ.BP_7-62x54R_FMJ_C",
			_7_62x54R_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x54R_TR.BP_7-62x54R_TR_C",
			_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x39_FMJ.BP_9x39_FMJ_C",
			_9x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x39_TR.BP_9x39_TR_C",
		},

	},

	Consumable = {
		CigPack = "/Game/ITR2/BPs/Items/Consumable/BP_CigPack.BP_CigPack_C",
		CrackerPack = "/Game/ITR2/BPs/Items/Consumable/BP_CrackerPack.BP_CrackerPack_C",
		CannedCan_Fish = "/Game/ITR2/BPs/Items/Consumable/BP_CannedCan_Fish.BP_CannedCan_Fish_C",
		Cig = "/Game/ITR2/BPs/Items/Consumable/BP_Cig.BP_Cig_C",
		CanFish = "/Game/ITR2/BPs/Items/Consumable/BP_CanFish.BP_CanFish_C",
		Cracker = "/Game/ITR2/BPs/Items/Consumable/BP_Cracker.BP_Cracker_C",
		Cracker_bitten_1 = "/Game/ITR2/BPs/Items/Consumable/BP_Cracker_bitten_1.BP_Cracker_bitten_1_C",
		Cracker_bitten_2 = "/Game/ITR2/BPs/Items/Consumable/BP_Cracker_bitten_2.BP_Cracker_bitten_2_C",
		Injector_QuickHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_QuickHeal.BP_Injector_QuickHeal_C",
		Injector_SlowHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_SlowHeal.BP_Injector_SlowHeal_C",
		Injector_FullHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_FullHeal.BP_Injector_FullHeal_C",
		Chocolate = "/Game/ITR2/BPs/Items/Consumable/BP_Chocolate.BP_Chocolate_C",
	},

	Misc = {
		Lighter = "/Game/ITR2/BPs/Items/Misc/BP_Lighter.BP_Lighter_C",
		Basketball_ball = "/Game/ITR2/BPs/Items/Misc/BP_Basketball_ball.BP_Basketball_Ball_C",
		CassettePlayer = "/Game/ITR2/BPs/Items/Misc/BP_CassettePlayer.BP_CassettePlayer_C",
		Note = "/Game/ITR2/BPs/Items/Misc/BP_Note.BP_Note_C",
		Misc_Item_Bucket_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Bucket_1.BP_Misc_Item_Bucket_1_C",
		Misc_Item_CupFotTea = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_CupFotTea.BP_Misc_Item_CupFotTea_C",
		Misc_Item_Mug = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Mug.BP_Misc_Item_Mug_C",
		Misc_Item_CarpetBeater = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_CarpetBeater.BP_Misc_Item_CarpetBeater_C",
		Misc_Item_Pan_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Pan_1.BP_Misc_Item_Pan_1_C",
		Misc_Item_Pan_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Pan_2.BP_Misc_Item_Pan_2_C",
		Misc_Item_Plate = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Plate.BP_Misc_Item_Plate_C",
		Misc_Item_Can_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Can_1.BP_Misc_Item_Can_1_C",
		Misc_Item_Padlock = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Padlock.BP_Misc_Item_Padlock_C",
		Misc_Item_Soap = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Soap.BP_Misc_Item_Soap_C",
		Misc_Item_Spoon = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Spoon.BP_Misc_Item_Spoon_C",
		Misc_Item_ToyCube = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube.BP_Misc_Item_ToyCube_C",
		Misc_Item_Wrench = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Wrench.BP_Misc_Item_Wrench_C",
		Misc_Item_Mug2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Mug2.BP_Misc_Item_Mug2_C",
		Misc_Item_Mug3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Mug3.BP_Misc_Item_Mug3_C",
		Misc_Item_Nevalashka = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Nevalashka.BP_Misc_Item_Nevalashka_C",
		Misc_Item_Teddy = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Teddy.BP_Misc_Item_Teddy_C",
		Misc_Item_Radio = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Radio.BP_Misc_Item_Radio_C",
		Misc_Item_Toy_Gun_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Toy_Gun_1.BP_Misc_Item_Toy_Gun_1_C",
		Misc_Item_Toy_Gun_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Toy_Gun_2.BP_Misc_Item_Toy_Gun_2_C",
		Misc_Item_Toy_Gun_3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Toy_Gun_3.BP_Misc_Item_Toy_Gun_3_C",
		Misc_Item_Phone = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Phone.BP_Misc_Item_Phone_C",
		Misc_Item_ToyCube_CH_1 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_1.BP_Misc_Item_ToyCube_CH_1_C",
		Misc_Item_ToyCube_CH_2 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_2.BP_Misc_Item_ToyCube_CH_2_C",
		Misc_Item_ToyCube_CH_3 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_3.BP_Misc_Item_ToyCube_CH_3_C",
		Misc_Item_ToyCube_CH_4 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_4.BP_Misc_Item_ToyCube_CH_4_C",
		Misc_Item_ToyCube_CH_5 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_5.BP_Misc_Item_ToyCube_CH_5_C",
		Misc_Item_ToyCube_CH_6 = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_ToyCube_CH_6.BP_Misc_Item_ToyCube_CH_6_C",
		Misc_Item_Rubick = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Item_Rubick.BP_Misc_Item_Rubick_C",
		Misc_Toy_Truck_Full = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Toy_Truck_Full.BP_Misc_Toy_Truck_Full_C",
		Misc_Clock = "/Game/ITR2/BPs/Items/Misc/Items/BP_Misc_Clock.BP_Misc_Clock_C",

		CheckersBoardGame = {
			BlackCheckersPack = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_BlackCheckersPack.BP_BlackCheckersPack_C",
			WhiteCheckersPack = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_WhiteCheckersPack.BP_WhiteCheckersPack_C",
			Checker_White_Item_New = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Checker_White_Item_New.BP_Checker_White_Item_New_C",
			Checker_Black_Item_New = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Checker_Black_Item_New.BP_Checker_Black_Item_New_C",
			Dice = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Dice.BP_Dice_C",
			Dice_Glass = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Dice_Glass.BP_Dice_Glass_C",
			BoardTable = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_BoardTable.BP_BoardTable_C",
		},

		Guitar = {
			Coin = "/Game/ITR2/BPs/Items/Misc/Guitar/BP_Coin.BP_Coin_C",
			Guitar = "/Game/ITR2/BPs/Items/Misc/Guitar/BP_Guitar.BP_Guitar_C",
		},

		AnniversaryItems = {
			Misc_Item_Toy_PechoAngry = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_Toy_PechoAngry.BP_Misc_Item_Toy_PechoAngry_C",
			Misc_Item_Toy_PechoLoving = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_Toy_PechoLoving.BP_Misc_Item_Toy_PechoLoving_C",
			Misc_Item_Toy_PechoQuiet = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_Toy_PechoQuiet.BP_Misc_Item_Toy_PechoQuiet_C",
			Misc_Item_AnniversaryCertificate = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_AnniversaryCertificate.BP_Misc_Item_AnniversaryCertificate_C",
			Misc_Item_MugAnniversary = "/Game/ITR2/BPs/Items/Misc/AnniversaryItems/BP_Misc_Item_MugAnniversary.BP_Misc_Item_MugAnniversary_C",
		},

		ShelfBoxes = {
			BoxForShelf_1 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_BoxForShelf_1.BP_BoxForShelf_1_C",
			BoxForShelf_2 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_BoxForShelf_2.BP_BoxForShelf_2_C",
			ShelfBox_LargeAmmo_3 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_LargeAmmo_3.BP_ShelfBox_LargeAmmo_3_C",
			ShelfBox_LargeAmmo_3_2 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_LargeAmmo_3_2.BP_ShelfBox_LargeAmmo_3_2_C",
			ShelfBox_LargeAmmo_6 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_LargeAmmo_6.BP_ShelfBox_LargeAmmo_6_C",
			ShelfBox_SmallAmmo_1 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_SmallAmmo_1.BP_ShelfBox_SmallAmmo_1_C",
			ShelfBox_SmallAmmo_t2 = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_SmallAmmo_t2.BP_ShelfBox_SmallAmmo_t2_C",
			ShelfBox_Plates = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_Plates.BP_ShelfBox_Plates_C",
			BoxForShelf_Weapon = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_BoxForShelf_Weapon.BP_BoxForShelf_Weapon_C",
			ShelfBox_SmallContainer = "/Game/ITR2/BPs/Items/Misc/ShelfBoxes/BP_ShelfBox_SmallContainer.BP_ShelfBox_SmallContainer_C",
		},

	},

	Artefacts = {
		Detector = "/Game/ITR2/BPs/Items/Artefacts/BP_Detector.BP_Detector_C",
		Detector_Lvl2 = "/Game/ITR2/BPs/Items/Artefacts/BP_Detector_Lvl2.BP_Detector_Lvl2_C",

		Nests = {
			StickyNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_StickyNest.BP_StickyNest_C",
			FragileNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_FragileNest.BP_FragileNest_C",
			MirrorShardsNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_MirrorShardsNest.BP_MirrorShardsNest_C",
			InvisibleNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_InvisibleNest.BP_InvisibleNest_C",
		},

		Arts = {
			MissionsArts = {
				Art_Mission1 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission1.BP_Art_Mission1_C",
				Art_Mission2 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission2.BP_Art_Mission2_C",
				Art_Mission3 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission3.BP_Art_Mission3_C",
				Art_Mission4 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission4.BP_Art_Mission4_C",
				Art_Mission5 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Mission5.BP_Art_Mission5_C",
				Art_TopPriority1 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_TopPriority1.BP_Art_TopPriority1_C",
				Art_TopPriority2 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_TopPriority2.BP_Art_TopPriority2_C",
				Art_TopPriority3 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_TopPriority3.BP_Art_TopPriority3_C",
				Art_TopPriority4 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_TopPriority4.BP_Art_TopPriority4_C",
			},

		},

	},

	Flashlights = {
		Flashlight_Handheld = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_Handheld.BP_Flashlight_Handheld_C",
		Flashlight_Pocket = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_Pocket.BP_Flashlight_Pocket_C",
		Flashlight_HeadLamp = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_HeadLamp.BP_Flashlight_HeadLamp_C",
	},

	Equipment = {
		Helmets = {
			Helmet_SSH_94 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_SSH_94.BP_Helmet_SSH_94_C",
			Helmet_Pasgt = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_Pasgt.BP_Helmet_Pasgt_C",
			Helmet_FAST = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_FAST.BP_Helmet_FAST_C",

			Helmet_Attachments = {
				PVS14 = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_PVS14.BP_PVS14_C",
				Armored_Visor = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_Armored_Visor.BP_Armored_Visor_C",
				NV_JArm = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_NV_JArm.BP_NV_JArm_C",
				NV_Mount = "/Game/ITR2/BPs/Items/Equipment/Helmets/Helmet_Attachments/BP_NV_Mount.BP_NV_Mount_C",
			},

		},

		Tablet = {
			Tablet = "/Game/ITR2/BPs/Items/Equipment/Tablet/BP_Tablet.BP_Tablet_C",
		},

		Armors = {
			ArmorPlate_Light = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Light.BP_ArmorPlate_Light_C",
			ArmorPlate_Medium = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Medium.BP_ArmorPlate_Medium_C",
			ArmorPlate_Heavy = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Heavy.BP_ArmorPlate_Heavy_C",
			Armor_Modular_Light_Sand = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Light_Sand.BP_Armor_Modular_Light_Sand_C",
			Armor_Modular_Light_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Light_Black_CH.BP_Armor_Modular_Light_Black_CH_C",
			Armor_Modular_Light_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Light_Camo_CH.BP_Armor_Modular_Light_Camo_CH_C",
			Armor_Modular_Heavy_Sand = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Heavy_Sand.BP_Armor_Modular_Heavy_Sand_C",
			Armor_Modular_Heavy_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Heavy_Black_CH.BP_Armor_Modular_Heavy_Black_CH_C",
			Armor_Modular_Heavy_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_Armor_Modular_Heavy_Camo_CH.BP_Armor_Modular_Heavy_Camo_CH_C",
		},

		Anti_Distortion_Helmets = {
			ADH_1 = "/Game/ITR2/BPs/Items/Equipment/Anti_Distortion_Helmets/BP_ADH_1.BP_ADH_1_C",
			ADH_1_Prototype = "/Game/ITR2/BPs/Items/Equipment/Anti_Distortion_Helmets/BP_ADH_1_Prototype.BP_ADH_1_Prototype_C",
		},

		Modules = {
			Module_ItemSlot = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemSlot.BP_Module_ItemSlot_C",
			Module_HelmetHook = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_HelmetHook.BP_Module_HelmetHook_C",
			Module_ItemPatch_UNPSC = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_UNPSC.BP_Module_ItemPatch_UNPSC_C",
			Module_ItemPatch_ITR1_Red = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_ItemPatch_ITR1_Red.BP_Module_ItemPatch_ITR1_Red_C",
			Module_TabletPocket = "/Game/ITR2/BPs/Items/Equipment/Modules/BP_Module_TabletPocket.BP_Module_TabletPocket_C",

			Sand = {
				Module_DropPouch_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_DropPouch_Sand.BP_Module_DropPouch_Sand_C",
				Module_MagPouch_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouch_Sand.BP_Module_MagPouch_Sand_C",
				Module_MagPouch_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouch_NoMolle_Sand.BP_Module_MagPouch_NoMolle_Sand_C",
				Module_HolsterPistol_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_L_Sand.BP_Module_HolsterPistol_L_Sand_C",
				Module_HolsterPistol_L_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_L_NoMolle_Sand.BP_Module_HolsterPistol_L_NoMolle_Sand_C",
				Module_HolsterPistol_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_R_Sand.BP_Module_HolsterPistol_R_Sand_C",
				Module_HolsterPistol_R_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterPistol_R_NoMolle_Sand.BP_Module_HolsterPistol_R_NoMolle_Sand_C",
				Module_HolsterRifle_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_L_Sand.BP_Module_HolsterRifle_L_Sand_C",
				Module_HolsterRifle_L_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_L_NoMolle_Sand.BP_Module_HolsterRifle_L_NoMolle_Sand_C",
				Module_HolsterRifle_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_R_Sand.BP_Module_HolsterRifle_R_Sand_C",
				Module_HolsterRifle_R_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_HolsterRifle_R_NoMolle_Sand.BP_Module_HolsterRifle_R_NoMolle_Sand_C",
				Module_AmmoPouch_12_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_12_Sand.BP_Module_AmmoPouch_12_Sand_C",
				Module_AmmoPouch_8_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_8_Sand.BP_Module_AmmoPouch_8_Sand_C",
				Module_AmmoPouch_6_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_6_Sand.BP_Module_AmmoPouch_6_Sand_C",
				Module_AmmoPouch_4_1_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_4_1_Sand.BP_Module_AmmoPouch_4_1_Sand_C",
				Module_AmmoPouch_4_2_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoPouch_4_2_Sand.BP_Module_AmmoPouch_4_2_Sand_C",
				Module_AmmoBoxPouch_Vertical_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Vertical_L_Sand.BP_Module_AmmoBoxPouch_Vertical_L_Sand_C",
				Module_AmmoBoxPouch_Vertical_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Vertical_R_Sand.BP_Module_AmmoBoxPouch_Vertical_R_Sand_C",
				Module_AmmoBoxPouch_Horizontal_R_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Horizontal_R_Sand.BP_Module_AmmoBoxPouch_Horizontal_R_Sand_C",
				Module_AmmoBoxPouch_Horizontal_L_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_AmmoBoxPouch_Horizontal_L_Sand.BP_Module_AmmoBoxPouch_Horizontal_L_Sand_C",
				Module_MagPouchPistol_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouchPistol_Sand.BP_Module_MagPouchPistol_Sand_C",
				Module_MagPouchPistol_NoMolle_Sand = "/Game/ITR2/BPs/Items/Equipment/Modules/Sand/BP_Module_MagPouchPistol_NoMolle_Sand.BP_Module_MagPouchPistol_NoMolle_Sand_C",
			},

			Black = {
				Module_DropPouch_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_DropPouch_Black_CH.BP_Module_DropPouch_Black_CH_C",
				Module_MagPouch_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_MagPouch_Black_CH.BP_Module_MagPouch_Black_CH_C",
				Module_MagPouch_NoMolle_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_MagPouch_NoMolle_Black_CH.BP_Module_MagPouch_NoMolle_Black_CH_C",
				Module_HolsterPistol_L_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterPistol_L_Black_CH.BP_Module_HolsterPistol_L_Black_CH_C",
				Module_HolsterPistol_L_NoMolle_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterPistol_L_NoMolle_Black_CH.BP_Module_HolsterPistol_L_NoMolle_Black_CH_C",
				Module_HolsterPistol_R_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterPistol_R_Black_CH.BP_Module_HolsterPistol_R_Black_CH_C",
				Module_HolsterPistol_R_NoMolle_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterPistol_R_NoMolle_Black_CH.BP_Module_HolsterPistol_R_NoMolle_Black_CH_C",
				Module_HolsterRifle_L_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterRifle_L_Black_CH.BP_Module_HolsterRifle_L_Black_CH_C",
				Module_HolsterRifle_L_NoMolle_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterRifle_L_NoMolle_Black_CH.BP_Module_HolsterRifle_L_NoMolle_Black_CH_C",
				Module_HolsterRifle_R_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterRifle_R_Black_CH.BP_Module_HolsterRifle_R_Black_CH_C",
				Module_HolsterRifle_R_NoMolle_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_HolsterRifle_R_NoMolle_Black_CH.BP_Module_HolsterRifle_R_NoMolle_Black_CH_C",
				Module_AmmoPouch_12_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoPouch_12_Black_CH.BP_Module_AmmoPouch_12_Black_CH_C",
				Module_AmmoPouch_8_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoPouch_8_Black_CH.BP_Module_AmmoPouch_8_Black_CH_C",
				Module_AmmoPouch_6_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoPouch_6_Black_CH.BP_Module_AmmoPouch_6_Black_CH_C",
				Module_AmmoPouch_4_1_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoPouch_4_1_Black_CH.BP_Module_AmmoPouch_4_1_Black_CH_C",
				Module_AmmoPouch_4_2_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoPouch_4_2_Black_CH.BP_Module_AmmoPouch_4_2_Black_CH_C",
				Module_AmmoBoxPouch_Vertical_L_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoBoxPouch_Vertical_L_Black_CH.BP_Module_AmmoBoxPouch_Vertical_L_Black_CH_C",
				Module_AmmoBoxPouch_Vertical_R_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoBoxPouch_Vertical_R_Black_CH.BP_Module_AmmoBoxPouch_Vertical_R_Black_CH_C",
				Module_AmmoBoxPouch_Horizontal_R_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoBoxPouch_Horizontal_R_Black_CH.BP_Module_AmmoBoxPouch_Horizontal_R_Black_CH_C",
				Module_AmmoBoxPouch_Horizontal_L_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_AmmoBoxPouch_Horizontal_L_Black_CH.BP_Module_AmmoBoxPouch_Horizontal_L_Black_CH_C",
				Module_MagPouchPistol_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_MagPouchPistol_Black_CH.BP_Module_MagPouchPistol_Black_CH_C",
				Module_MagPouchPistol_NoMolle_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Black/BP_Module_MagPouchPistol_NoMolle_Black_CH.BP_Module_MagPouchPistol_NoMolle_Black_CH_C",
			},

			Camo = {
				Module_DropPouch_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_DropPouch_Camo_CH.BP_Module_DropPouch_Camo_CH_C",
				Module_MagPouch_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_MagPouch_Camo_CH.BP_Module_MagPouch_Camo_CH_C",
				Module_MagPouch_NoMolle_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_MagPouch_NoMolle_Camo_CH.BP_Module_MagPouch_NoMolle_Camo_CH_C",
				Module_HolsterPistol_L_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterPistol_L_Camo_CH.BP_Module_HolsterPistol_L_Camo_CH_C",
				Module_HolsterPistol_L_NoMolle_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterPistol_L_NoMolle_Camo_CH.BP_Module_HolsterPistol_L_NoMolle_Camo_CH_C",
				Module_HolsterPistol_R_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterPistol_R_Camo_CH.BP_Module_HolsterPistol_R_Camo_CH_C",
				Module_HolsterPistol_R_NoMolle_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterPistol_R_NoMolle_Camo_CH.BP_Module_HolsterPistol_R_NoMolle_Camo_CH_C",
				Module_HolsterRifle_L_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterRifle_L_Camo_CH.BP_Module_HolsterRifle_L_Camo_CH_C",
				Module_HolsterRifle_L_NoMolle_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterRifle_L_NoMolle_Camo_CH.BP_Module_HolsterRifle_L_NoMolle_Camo_CH_C",
				Module_HolsterRifle_R_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterRifle_R_Camo_CH.BP_Module_HolsterRifle_R_Camo_CH_C",
				Module_HolsterRifle_R_NoMolle_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_HolsterRifle_R_NoMolle_Camo_CH.BP_Module_HolsterRifle_R_NoMolle_Camo_CH_C",
				Module_AmmoPouch_12_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoPouch_12_Camo_CH.BP_Module_AmmoPouch_12_Camo_CH_C",
				Module_AmmoPouch_8_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoPouch_8_Camo_CH.BP_Module_AmmoPouch_8_Camo_CH_C",
				Module_AmmoPouch_6_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoPouch_6_Camo_CH.BP_Module_AmmoPouch_6_Camo_CH_C",
				Module_AmmoPouch_4_1_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoPouch_4_1_Camo_CH.BP_Module_AmmoPouch_4_1_Camo_CH_C",
				Module_AmmoPouch_4_2_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoPouch_4_2_Camo_CH.BP_Module_AmmoPouch_4_2_Camo_CH_C",
				Module_AmmoBoxPouch_Vertical_L_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoBoxPouch_Vertical_L_Camo_CH.BP_Module_AmmoBoxPouch_Vertical_L_Camo_CH_C",
				Module_AmmoBoxPouch_Vertical_R_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoBoxPouch_Vertical_R_Camo_CH.BP_Module_AmmoBoxPouch_Vertical_R_Camo_CH_C",
				Module_AmmoBoxPouch_Horizontal_R_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoBoxPouch_Horizontal_R_Camo_CH.BP_Module_AmmoBoxPouch_Horizontal_R_Camo_CH_C",
				Module_AmmoBoxPouch_Horizontal_L_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_AmmoBoxPouch_Horizontal_L_Camo_CH.BP_Module_AmmoBoxPouch_Horizontal_L_Camo_CH_C",
				Module_MagPouchPistol_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_MagPouchPistol_Camo_CH.BP_Module_MagPouchPistol_Camo_CH_C",
				Module_MagPouchPistol_NoMolle_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Modules/Camo/BP_Module_MagPouchPistol_NoMolle_Camo_CH.BP_Module_MagPouchPistol_NoMolle_Camo_CH_C",
			},

		},

		Vests = {
			Vest_Modular_Sand = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Modular_Sand.BP_Vest_Modular_Sand_C",
			Vest_Modular_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Modular_Black_CH.BP_Vest_Modular_Black_CH_C",
			Vest_Modular_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Modular_Camo_CH.BP_Vest_Modular_Camo_CH_C",
		},

		Backpacks = {
			BackPack_Small_Modular_Sand = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Small_Modular_Sand.BP_BackPack_Small_Modular_Sand_C",
			BackPack_Small_Modular_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Small_Modular_Black_CH.BP_BackPack_Small_Modular_Black_CH_C",
			BackPack_Small_Modular_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Small_Modular_Camo_CH.BP_BackPack_Small_Modular_Camo_CH_C",
			BackPack_Medium_Modular_Sand = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Medium_Modular_Sand.BP_BackPack_Medium_Modular_Sand_C",
			BackPack_Medium_Modular_Black_CH = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Medium_Modular_Black_CH.BP_BackPack_Medium_Modular_Black_CH_C",
			BackPack_Medium_Modular_Camo_CH = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Medium_Modular_Camo_CH.BP_BackPack_Medium_Modular_Camo_CH_C",
		},
	},

	Valuables = {
		ValuableItem_Cup = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Cup.BP_ValuableItem_Cup_C",
		ValuableItem_Sugar = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Sugar.BP_ValuableItem_Sugar_C",
		ValuableItem_Wrench = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Wrench.BP_ValuableItem_Wrench_C",
		ValuableItem_Soap = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Soap.BP_ValuableItem_Soap_C",
		ValuableItem_Spoon = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Spoon.BP_ValuableItem_Spoon_C",
		ValuableItem_CubeToy = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_CubeToy.BP_ValuableItem_CubeToy_C",
		ValuableItem_Lock = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Lock.BP_ValuableItem_Lock_C",
		ValuableItem_Nevalashka = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Nevalashka.BP_ValuableItem_Nevalashka_C",
		ValuableItem_Rubick = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Rubick.BP_ValuableItem_Rubick_C",
		ValuableItem_Brush = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Brush.BP_ValuableItem_Brush_C",
		ValuableItem_alarm_Clock = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_alarm_Clock.BP_ValuableItem_alarm_Clock_C",
		ValuableItem_Bulb = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Bulb.BP_ValuableItem_Bulb_C",

		Ashes = {
			Ash_small = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_small.BP_Ash_small_C",
			Ash_Medium = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Medium.BP_Ash_Medium_C",
			Ash_Big = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Big.BP_Ash_Big_C",
			Ash_Item1 = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Item1.BP_Ash_Item1_C",
			Ash_Item2 = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Item2.BP_Ash_Item2_C",
			Ash_Item3 = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Item3.BP_Ash_Item3_C",
		},

		Arts = {
			ValuableArt_1 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_1.BP_ValuableArt_1_C",
			ValuableArt_2 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_2.BP_ValuableArt_2_C",
			ValuableArt_3 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_3.BP_ValuableArt_3_C",
			ValuableArt_4 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_4.BP_ValuableArt_4_C",
			ValuableArt_5 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_5.BP_ValuableArt_5_C",
		},
	},

	MissionItems = {
		TripodBase = "/Game/ITR2/BPs/Items/MissionItems/BP_TripodBase.BP_TripodBase_C",
		MissionCase = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionCase.BP_MissionCase_C",
		MissionItem = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem.BP_MissionItem_C",
		MissionItem2 = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem2.BP_MissionItem2_C",
		MissionItem3 = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem3.BP_MissionItem3_C",
		MissionTripodSM = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionTripodSM.BP_MissionTripodSM_C",
		MissionTripodSM_Broken = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionTripodSM_Broken.BP_MissionTripodSM_Broken_C",
		MissionItem3_TopPriority = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem3_TopPriority.BP_MissionItem3_TopPriority_C",
		MissionItem_Tripod2 = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem_Tripod2.BP_MissionItem_Tripod2_C",
	},

	Player = {
		PlayerDeathPoint = "/Game/ITR2/BPs/Player/BP_PlayerDeathPoint.BP_PlayerDeathPoint_C",
	},

	QA = {
		QAEnemyCounter = "/Game/ITR2/BPs/QA/BP_QAEnemyCounter.BP_QAEnemyCounter_C",
		QARangefinder = "/Game/ITR2/BPs/QA/BP_QARangefinder.BP_QARangefinder_C",
	},

	Cleaning = {
		OilSpray = "/Game/ITR2/BPs/Items/Cleaning/BP_OilSpray.BP_OilSpray_C",
		CleaningBrush = "/Game/ITR2/BPs/Items/Cleaning/BP_CleaningBrush.BP_CleaningBrush_C",
		Cleaning_ToothBrush_CH = "/Game/ITR2/BPs/Items/Cleaning/BP_Cleaning_ToothBrush_CH.BP_Cleaning_ToothBrush_CH_C",
	},

	Walkie_talkie = {
		Walkie_talkie = "/Game/ITR2/BPs/Items/Walkie_talkie/BP_Walkie_talkie.BP_Walkie_talkie_C",
	},
}

return Items