-- AUTO GENERATED BY ITR2 ITEM UPDATE SCRIPT--
local Items = {

    Probes = {
        ProbeSack = "/Game/ITR2/BPs/Items/Probes/BP_ProbeSack.BP_ProbeSack_C",
        RadiusAmmo_Probe = "/Game/ITR2/BPs/Items/Probes/BP_RadiusAmmo_Probe.BP_RadiusAmmo_Probe_C"
    },

    Firearms = {

        Primary = {

            AK74 = {
                AK_74_Mag_Red = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Red.BP_AK_74_Mag_Red_C",
                AK_74_Mag_Black = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Black.BP_AK_74_Mag_Black_C",
                AK_74_Mag_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK_74_Mag_Long.BP_AK_74_Mag_Long_C",
                AKSu74N = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AKSu74N.BP_AKSu74N_C",
                AK74N = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74N.BP_AK74N_C",
                AK74M = "/Game/ITR2/BPs/Items/Firearms/Primary/AK74/BP_AK74M.BP_AK74M_C"
            },

            SKS = {
                SKS_Mag_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_Mag_Short.BP_SKS_Mag_Short_C",
                SKS = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS.BP_SKS_C",
                SKS_M = "/Game/ITR2/BPs/Items/Firearms/Primary/SKS/BP_SKS_M.BP_SKS_M_C"
            },

            Groza = {
                Groza_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza_Mag.BP_Groza_Mag_C",
                Groza = "/Game/ITR2/BPs/Items/Firearms/Primary/Groza/BP_Groza.BP_Groza_C"
            },

            Saiga = {
                Saiga_Mag_Short2 = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Mag_Short2.BP_Saiga_Mag_Short2_C",
                Saiga_Mag_Long = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga_Mag_Long.BP_Saiga_Mag_Long_C",
                Saiga = "/Game/ITR2/BPs/Items/Firearms/Primary/Saiga/BP_Saiga.BP_Saiga_C"
            },

            Val_and_VSS = {
                VSS_Mag_Short = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VSS_Mag_Short.BP_VSS_Mag_Short_C",
                AS_Val_Mag_Med = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_AS_Val_Mag_Med.BP_AS_Val_Mag_Med_C",
                VSS = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_VSS.BP_VSS_C",
                AS_VAL = "/Game/ITR2/BPs/Items/Firearms/Primary/Val_and_VSS/BP_AS_VAL.BP_AS_VAL_C"
            },

            Kedr = {
                Kedr_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Kedr/BP_Kedr_Mag.BP_Kedr_Mag_C",
                Kedr = "/Game/ITR2/BPs/Items/Firearms/Primary/Kedr/BP_Kedr.BP_Kedr_C"
            },

            Bizon = {
                Bizon_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon_Mag.BP_Bizon_Mag_C",
                Bizon = "/Game/ITR2/BPs/Items/Firearms/Primary/Bizon/BP_Bizon.BP_Bizon_C"
            },

            AKM = {
                AKM_Mag = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM_Mag.BP_AKM_Mag_C",
                AKM = "/Game/ITR2/BPs/Items/Firearms/Primary/AKM/BP_AKM.BP_AKM_C"
            },

            IZh_27 = {
                Iz27_SawOff = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_SawOff.BP_Iz27_SawOff_C",
                Iz27 = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27.BP_Iz27_C",
                Iz27_M = "/Game/ITR2/BPs/Items/Firearms/Primary/IZh-27/BP_Iz27_M.BP_Iz27_M_C"
            }

        },

        Secondary = {

            PM = {
                Mag_PM = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_Mag_PM.BP_Mag_PM_C",
                Mag_PM_Long = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_Mag_PM_Long.BP_Mag_PM_Long_C",
                PM = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM.BP_PM_C",
                PM_mod = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM_mod.BP_PM_mod_C",
                PM_Replica = "/Game/ITR2/BPs/Items/Firearms/Secondary/PM/BP_PM_Replica.BP_PM_Replica_C"
            },

            Gsh18 = {
                Mag_Gsh18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Mag_Gsh18.BP_Mag_Gsh18_C",
                Gsh18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Gsh18/BP_Gsh18.BP_Gsh18_C"
            },

            Beretta = {
                Mag_Beretta = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Mag_Beretta.BP_Mag_Beretta_C",
                Beretta = "/Game/ITR2/BPs/Items/Firearms/Secondary/Beretta/BP_Beretta.BP_Beretta_C"
            },

            Glock_18 = {
                Mag_Glock_18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Mag_Glock_18.BP_Mag_Glock_18_C",
                Mag_Glock_18_Long = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Mag_Glock_18_Long.BP_Mag_Glock_18_Long_C",
                Glock_18 = "/Game/ITR2/BPs/Items/Firearms/Secondary/Glock_18/BP_Glock_18.BP_Glock_18_C"
            }

        },

        Attachments = {

            Scopes = {
                Scope_PSO = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_PSO.BP_Scope_PSO_C",
                RDS_Cobra = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_Cobra.BP_RDS_Cobra_C",
                RDS_PK6 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_RDS_PK6.BP_RDS_PK6_C",
                Scope_HG = "/Game/ITR2/BPs/Items/Firearms/Attachments/Scopes/BP_Scope_HG.BP_Scope_HG_C"
            },

            Rails = {
                Rail_45deg = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_45deg.BP_Rail_45deg_C",
                Rail_45deg_R = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_45deg_R.BP_Rail_45deg_R_C",
                Rail_PistolOverUnder = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_Rail_PistolOverUnder.BP_Rail_PistolOverUnder_C",
                DovetailToRail = "/Game/ITR2/BPs/Items/Firearms/Attachments/Rails/BP_DovetailToRail.BP_DovetailToRail_C"
            },

            Illumination = {
                Att_Flashlight_small = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Flashlight_small.BP_Att_Flashlight_small_C",
                Att_Pointer_small = "/Game/ITR2/BPs/Items/Firearms/Attachments/Illumination/BP_Att_Pointer_small.BP_Att_Pointer_small_C"
            },

            Muzzles = {

                AK = {
                    MuzzleAKSu_Base2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAKSu_Base2.BP_MuzzleAKSu_Base2_C",
                    MuzzleAK_Base = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_Base.BP_MuzzleAK_Base_C",
                    MuzzleAK_DTK2 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_DTK2.BP_MuzzleAK_DTK2_C",
                    MuzzleAK_DTK1 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_DTK1.BP_MuzzleAK_DTK1_C",
                    MuzzleAK_M11 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Muzzles/AK/BP_MuzzleAK_M11.BP_MuzzleAK_M11_C"
                }

            },

            Silencers = {
                Silencer_5_45 = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_5_45.BP_Silencer_5_45_C",
                Silencer_Pistol = "/Game/ITR2/BPs/Items/Firearms/Attachments/Silencers/BP_Silencer_Pistol.BP_Silencer_Pistol_C"
            }

        }

    },

    Ammo = {

        AmmoBox = {
            AmmoBox_12x70_BuckShot = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_BuckShot.BP_AmmoBox_12x70_BuckShot_C",
            AmmoBox_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_FMJ.BP_AmmoBox_9x18_FMJ_C",
            AmmoBox_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x19_FMJ.BP_AmmoBox_9x19_FMJ_C",
            AmmoBox_545x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_FMJ.BP_AmmoBox_545x39_FMJ_C",
            AmmoBox_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_5-56x45_FMJ.BP_AmmoBox_5-56x45_FMJ_C",
            AmmoBox_7_62x54R_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x54R_FMJ.BP_AmmoBox_7-62x54R_FMJ_C",
            AmmoBox_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x51_FMJ.BP_AmmoBox_7-62x51_FMJ_C",
            AmmoBox_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x39_FMJ.BP_AmmoBox_7-62x39_FMJ_C",
            AmmoBox_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x39_FMJ.BP_AmmoBox_9x39_FMJ_C",
            AmmoBox_12x70_Slug = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_Slug.BP_AmmoBox_12x70_Slug_C",
            AmmoBox_12x70_SlugTracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_12x70_SlugTracer.BP_AmmoBox_12x70_SlugTracer_C",
            AmmoBox_9x18_PlusP = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_PlusP.BP_AmmoBox_9x18_PlusP_C",
            AmmoBox_545x39_BP = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_BP.BP_AmmoBox_545x39_BP_C",
            AmmoBox_9x18_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x18_Tracer.BP_AmmoBox_9x18_Tracer_C",
            AmmoBox_9x19_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x19_Tracer.BP_AmmoBox_9x19_Tracer_C",
            AmmoBox_545x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_545x39_Tracer.BP_AmmoBox_545x39_Tracer_C",
            AmmoBox_5_56x45_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_5-56x45_Tracer.BP_AmmoBox_5-56x45_Tracer_C",
            AmmoBox_7_62x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x39_Tracer.BP_AmmoBox_7-62x39_Tracer_C",
            AmmoBox_7_62x51_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x51_Tracer.BP_AmmoBox_7-62x51_Tracer_C",
            AmmoBox_7_62x54R_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_7-62x54R_Tracer.BP_AmmoBox_7-62x54R_Tracer_C",
            AmmoBox_9x39_Tracer = "/Game/ITR2/BPs/Items/Ammo/AmmoBox/BP_AmmoBox_9x39_Tracer.BP_AmmoBox_9x39_Tracer_C"
        },

        LargeAmmoBox = {
            AmmoBoxLarge_12x70_BuckShot = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_BuckShot.BP_AmmoBoxLarge_12x70_BuckShot_C",
            AmmoBoxLarge_12x70_Slug = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_Slug.BP_AmmoBoxLarge_12x70_Slug_C",
            AmmoBoxLarge_12x70_SlugTR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_12x70_SlugTR.BP_AmmoBoxLarge_12x70_SlugTR_C",
            AmmoBoxLarge_9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x18_FMJ.BP_AmmoBoxLarge_9x18_FMJ_C",
            AmmoBoxLarge_9x18_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x18_TR.BP_AmmoBoxLarge_9x18_TR_C",
            AmmoBoxLarge_9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x19_FMJ.BP_AmmoBoxLarge_9x19_FMJ_C",
            AmmoBoxLarge_9x19_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x19_TR.BP_AmmoBoxLarge_9x19_TR_C",
            AmmoBoxLarge_5_45x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_45x39_FMJ.BP_AmmoBoxLarge_5_45x39_FMJ_C",
            AmmoBoxLarge_5_45x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_45x39_TR.BP_AmmoBoxLarge_5_45x39_TR_C",
            AmmoBoxLarge_5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_56x45_FMJ.BP_AmmoBoxLarge_5_56x45_FMJ_C",
            AmmoBoxLarge_5_56x45_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_5_56x45_TR.BP_AmmoBoxLarge_5_56x45_TR_C",
            AmmoBoxLarge_7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x39_FMJ.BP_AmmoBoxLarge_7_62x39_FMJ_C",
            AmmoBoxLarge_7_62x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x39_TR.BP_AmmoBoxLarge_7_62x39_TR_C",
            AmmoBoxLarge_7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x51_FMJ.BP_AmmoBoxLarge_7_62x51_FMJ_C",
            AmmoBoxLarge_7_62x51_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x51_TR.BP_AmmoBoxLarge_7_62x51_TR_C",
            AmmoBoxLarge_7_62x54_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x54_FMJ.BP_AmmoBoxLarge_7_62x54_FMJ_C",
            AmmoBoxLarge_7_62x54_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_7_62x54_TR.BP_AmmoBoxLarge_7_62x54_TR_C",
            AmmoBoxLarge_9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x39_FMJ.BP_AmmoBoxLarge_9x39_FMJ_C",
            AmmoBoxLarge_9x39_TR = "/Game/ITR2/BPs/Items/Ammo/LargeAmmoBox/BP_AmmoBoxLarge_9x39_TR.BP_AmmoBoxLarge_9x39_TR_C"
        },

        Cartridges = {
            _5_45x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_FMJ.BP_5-45x39_FMJ_C",
            _5_45x39_BP = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_BP.BP_5-45x39_BP_C",
            _5_45x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-45x39_TR.BP_5-45x39_TR_C",
            _9x18_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_FMJ.BP_9x18_FMJ_C",
            _9x18_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_TR.BP_9x18_TR_C",
            _9x18_PlusP = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x18_PlusP.BP_9x18_PlusP_C",
            _12g_Buckshot = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_Buckshot.BP_12g_Buckshot_C",
            _12g_Slug = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_Slug.BP_12g_Slug_C",
            _12g_SlugTracer = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_12g_SlugTracer.BP_12g_SlugTracer_C",
            _9x19_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x19_FMJ.BP_9x19_FMJ_C",
            _9x19_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x19_TR.BP_9x19_TR_C",
            _7_62x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x39_FMJ.BP_7-62x39_FMJ_C",
            _7_62x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x39_TR.BP_7-62x39_TR_C",
            _9x39_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x39_FMJ.BP_9x39_FMJ_C",
            _9x39_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_9x39_TR.BP_9x39_TR_C",
            _7_62x54R_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x54R_FMJ.BP_7-62x54R_FMJ_C",
            _7_62x54R_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x54R_TR.BP_7-62x54R_TR_C",
            _5_56x45_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-56x45_FMJ.BP_5-56x45_FMJ_C",
            _5_56x45_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_5-56x45_TR.BP_5-56x45_TR_C",
            _7_62x51_FMJ = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x51_FMJ.BP_7-62x51_FMJ_C",
            _7_62x51_TR = "/Game/ITR2/BPs/Items/Ammo/Cartridges/BP_7-62x51_TR.BP_7-62x51_TR_C"
        }

    },

    Consumable = {
        CigPack = "/Game/ITR2/BPs/Items/Consumable/BP_CigPack.BP_CigPack_C",
        CrackerPack = "/Game/ITR2/BPs/Items/Consumable/BP_CrackerPack.BP_CrackerPack_C",
        CannedCan_Fish = "/Game/ITR2/BPs/Items/Consumable/BP_CannedCan_Fish.BP_CannedCan_Fish_C",
        Cig = "/Game/ITR2/BPs/Items/Consumable/BP_Cig.BP_Cig_C",
        CanFish = "/Game/ITR2/BPs/Items/Consumable/BP_CanFish.BP_CanFish_C",
        Cracker = "/Game/ITR2/BPs/Items/Consumable/BP_Cracker.BP_Cracker_C",
        Cracker_bitten_1 = "/Game/ITR2/BPs/Items/Consumable/BP_Cracker_bitten_1.BP_Cracker_bitten_1_C",
        Cracker_bitten_2 = "/Game/ITR2/BPs/Items/Consumable/BP_Cracker_bitten_2.BP_Cracker_bitten_2_C",
        Injector_QuickHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_QuickHeal.BP_Injector_QuickHeal_C",
        Injector_SlowHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_SlowHeal.BP_Injector_SlowHeal_C",
        Injector_FullHeal = "/Game/ITR2/BPs/Items/Consumable/BP_Injector_FullHeal.BP_Injector_FullHeal_C",
        Chocolate = "/Game/ITR2/BPs/Items/Consumable/BP_Chocolate.BP_Chocolate_C"
    },

    Artefacts = {
        Detector = "/Game/ITR2/BPs/Items/Artefacts/BP_Detector.BP_Detector_C",

        Nests = {
            StickyNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_StickyNest.0",
            FragileNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_FragileNest.0",
            MirrorShardsNest = "/Game/ITR2/BPs/Items/Artefacts/Nests/BP_MirrorShardsNest.1"
        },

        Arts = {

            MissionsArts = {
                Art_Neon = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_Neon.BP_Art_Neon_C",
                Art_M2 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_M2.BP_Art_M2_C",
                Art_M3 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_M3.BP_Art_M3_C",
                Art_M4 = "/Game/ITR2/BPs/Items/Artefacts/Arts/MissionsArts/BP_Art_M4.BP_Art_M4_C"
            }

        }

    },

    Flashlights = {
        Flashlight_Handheld = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_Handheld.BP_Flashlight_Handheld_C",
        Flashlight_Pocket = "/Game/ITR2/BPs/Items/Flashlights/BP_Flashlight_Pocket.BP_Flashlight_Pocket_C"
    },

    Equipment = {

        Helmets = {
            Helmet_SH40 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_SH40.BP_Helmet_SH40_C",
            Helmet_BH2 = "/Game/ITR2/BPs/Items/Equipment/Helmets/BP_Helmet_BH2.BP_Helmet_BH2_C"
        },

        Tablet = {
            Tablet = "/Game/ITR2/BPs/Items/Equipment/Tablet/BP_Tablet.BP_Tablet_C"
        },

        Backpacks = {
            BackPack_Start_Small = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Start_Small.BP_BackPack_Start_Small_C",
            BackPack_Small_1 = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Small_1.BP_BackPack_Small_1_C",
            BackPack_Medium_1 = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Medium_1.BP_BackPack_Medium_1_C",
            BackPack_Medium_2 = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Medium_2.BP_BackPack_Medium_2_C",
            BackPack_Large_1 = "/Game/ITR2/BPs/Items/Equipment/Backpacks/BP_BackPack_Large_1.BP_BackPack_Large_1_C"
        },

        Vests = {
            Vest_Start = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Start.BP_Vest_Start_C",
            Vest_Classic = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Classic.BP_Vest_Classic_C",
            Vest_Pistols = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Pistols.BP_Vest_Pistols_C",
            Vest_FrontGun_Only = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_FrontGun_Only.BP_Vest_FrontGun_Only_C",
            Vest_ClassicExpanded = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_ClassicExpanded.BP_Vest_ClassicExpanded_C",
            Vest_FrontGun_n_Pistol = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_FrontGun_n_Pistol.BP_Vest_FrontGun_n_Pistol_C",
            Vest_Start_L = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Start_L.BP_Vest_Start_L_C",
            Vest_Pistols_L = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Pistols_L.BP_Vest_Pistols_L_C",
            Vest_FrontGun_Only_L = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_FrontGun_Only_L.BP_Vest_FrontGun_Only_L_C",
            Vest_FrontGun_n_Pistol_L = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_FrontGun_n_Pistol_L.BP_Vest_FrontGun_n_Pistol_L_C",
            Vest_Classic_L = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_Classic_L.BP_Vest_Classic_L_C",
            Vest_ClassicExpanded_L = "/Game/ITR2/BPs/Items/Equipment/Vests/BP_Vest_ClassicExpanded_L.BP_Vest_ClassicExpanded_L_C"
        },

        Armors = {
            ArmorLight_Classic = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorLight_Classic.BP_ArmorLight_Classic_C",
            ArmorLight_Classic_L = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorLight_Classic_L.BP_ArmorLight_Classic_L_C",
            ArmorMedium_Classic = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorMedium_Classic.BP_ArmorMedium_Classic_C",
            ArmorMedium_Classic_L = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorMedium_Classic_L.BP_ArmorMedium_Classic_L_C",
            ArmorHeavy_Classic = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorHeavy_Classic.BP_ArmorHeavy_Classic_C",
            ArmorHeavy_Classic_L = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorHeavy_Classic_L.BP_ArmorHeavy_Classic_L_C",
            ArmorPlate_Light = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Light.BP_ArmorPlate_Light_C",
            ArmorPlate_Medium = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Medium.BP_ArmorPlate_Medium_C",
            ArmorPlate_Heavy = "/Game/ITR2/BPs/Items/Equipment/Armors/BP_ArmorPlate_Heavy.BP_ArmorPlate_Heavy_C"
        }

    },

    Valuables = {
        ValuableItem_Cup = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Cup.BP_ValuableItem_Cup_C",
        ValuableItem_Sugar = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Sugar.BP_ValuableItem_Sugar_C",
        ValuableItem_Wrench = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Wrench.BP_ValuableItem_Wrench_C",
        ValuableItem_Soap = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Soap.BP_ValuableItem_Soap_C",
        ValuableItem_Spoon = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Spoon.BP_ValuableItem_Spoon_C",
        ValuableItem_CubeToy = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_CubeToy.BP_ValuableItem_CubeToy_C",
        ValuableItem_Lock = "/Game/ITR2/BPs/Items/Valuables/BP_ValuableItem_Lock.BP_ValuableItem_Lock_C",

        Ashes = {
            Ash_small = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_small.BP_Ash_small_C",
            Ash_Medium = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Medium.BP_Ash_Medium_C",
            Ash_Big = "/Game/ITR2/BPs/Items/Valuables/Ashes/BP_Ash_Big.BP_Ash_Big_C"
        },

        Arts = {
            ValuableArt_1 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_1.BP_ValuableArt_1_C",
            ValuableArt_2 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_2.BP_ValuableArt_2_C",
            ValuableArt_3 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_3.BP_ValuableArt_3_C",
            ValuableArt_4 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_4.BP_ValuableArt_4_C",
            ValuableArt_5 = "/Game/ITR2/BPs/Items/Valuables/Arts/BP_ValuableArt_5.BP_ValuableArt_5_C"
        }

    },

    Misc = {
        Lighter = "/Game/ITR2/BPs/Items/Misc/BP_Lighter.BP_Lighter_C",
        Basketball_ball = "/Game/ITR2/BPs/Items/Misc/BP_Basketball_ball.BP_Basketball_Ball_C",

        CheckersBoardGame = {
            Checker_White_Item = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Checker_White_Item.BP_Checker_White_Item_C",
            Checker_Black_Item = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_Checker_Black_Item.BP_Checker_Black_Item_C",
            CheckersBoard = "/Game/ITR2/BPs/Items/Misc/CheckersBoardGame/BP_CheckersBoard.BP_CheckersBoard_C"
        }

    },

    MissionItems = {
        TripodBase = "/Game/ITR2/BPs/Items/MissionItems/BP_TripodBase.BP_TripodBase_C",
        MissionCase = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionCase.BP_MissionCase_C",
        MissionItem = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem.BP_MissionItem_C",
        MissionItem2 = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem2.BP_MissionItem2_C",
        MissionItem3 = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionItem3.BP_MissionItem3_C",
        MissionTripodSM = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionTripodSM.BP_MissionTripodSM_C",
        MissionTripodSM_Broken = "/Game/ITR2/BPs/Items/MissionItems/BP_MissionTripodSM_Broken.BP_MissionTripodSM_Broken_C",
        TripodDeactivated = "/Game/ITR2/BPs/Items/MissionItems/BP_TripodDeactivated.BP_TripodDeactivated_C"
    },

    Player = {
        PlayerDeathPoint = "/Game/ITR2/BPs/Player/BP_PlayerDeathPoint.BP_PlayerDeathPoint_C"
    },

    QA = {
        QARangefinder = "/Game/ITR2/BPs/QA/BP_QARangefinder.BP_QARangefinder_C"
    }

}

return Items
